### ISSUE TITLE
Response for Find References Request could contain more than one range for the uri

### ISSUE THREAD

**Issue by othomann** [Microsoft/language-server-protocol#102]
Right now with the protocol, the response is an array of Location. A location can contain only one range. This means that if you have two matches within the same file, you return two locations for the same uri that contains each a range.
Why not returning a new object that would have one uri and an array of ranges? Like this is also simpler for client to find out how many references were found within the same file.

**Comment by dbaeumer** [comment]
The reason for the current format was that result for references could come from a DB that doesn't necessarily have them grouped by file. So we thought the current protocol is more flexible in that regard. However I see the URI overhead in transport. Unless this is not a problem I opt to leave the protocol as is. 

Any objection to close.

**Comment by dbaeumer** [comment]
To keep the number of issues in our inbox at a manageable level, we’re closing issues that have been on the backlog for a long time but haven’t gained traction: we look at the number of votes the issue has received and the number of duplicate issues filed. Thank you for your time and understanding.

If you disagree and feel that this issue is crucial: we’re happy to listen and to reconsider.
