### ISSUE TITLE
Clarification for textDocument/onTypeFormatting for clients

### ISSUE THREAD

**Issue by rwols** [microsoft/language-server-protocol#1053]
The spec for textDocument/onTypeFormatting is very brief. Some questions for client implementors:

1) Should the editor first insert the character, and then after that do the textDocument/onTypeFormatting request?
2) Should the client first insert the character, and then do a textDocument/didChange, and then immediately after that a textDocument/onTypeformatting?
3) Is it allowed to have the editor first insert some heuristics for indenting (e.g. when typing a `\n`)?
4) Should the client ensure the character is *not* inserted before doing a textDocument/onTypeFormatting?
4a) If the character is not inserted, is it expected that the server will provide the text edits that will naturally insert it along?

From my understanding, it's supposed to work like this, but please correct me if it's wrong:

1) The editor inserts a char, possibly followed with more heuristic characters for indenting.
2) It *was* detected that a trigger was inserted for textDocument/onTypeFormatting
3) client ensures textDocument/didChange is notified, after which textDocument/onTypeFormatting is requested
4) Insert the received text edits as-is.

**Comment by dbaeumer** [comment]
@rwols your understanding makes sense. However in general I think we don't need to force a certain sequence since `onTypeFormatting ` should always act on the synced server state. Cients always need to flush all content changes to the server before that issue requests on a document.

I will close the issue. Please ping if you disagree with the statement from above.
