### ISSUE TITLE
document trace behavior of vscode

### ISSUE THREAD

**Issue by gorkem** [microsoft/language-server-protocol#109]
vscode jsonrpc client supports `$/setTraceNotification` and `$/logTraceNotification` notifications. Tracing is a very common feature for servers, hhould these be also added to the protocol?

**Comment by dbaeumer** [comment]
I decided not to because the transport might already have tracing options. Then having this is not necessary. I added this to our JSON-RPC implementation since we support stdio as transport which has not tracing.

**Comment by gorkem** [comment]
The advantage is this would work the same way on all supported operating systems.

**Comment by vladdu** [comment]
As a side question: what should servers do for messages they don't understand? For requests there is MethodNotFound error, while notifications should just be ignored?

**Comment by dbaeumer** [comment]
$ messages should/could be ignored since they depend on the implementation capabilities on the server. That is why I used the $ prefix.

**Comment by DanTup** [comment]
@dbaeumer Is there any info on what the `trace` property in the initialise params should do?

I'm looking for a way to make it easy for me to debug my server and considered using `trace==verbose` to mean that I can send lots of window/logMessages with verbose debug info (that way I can see it in LSP Inspector easily).

However, it's not clear if that is an expected thing to do, since there's also the `messages` option which seems like it's requesting logging of every message (but it wouldn't make sense to log messages by sending messages).

**Comment by DanTup** [comment]
I think having something standardised would make sense. Currently the `trace` property is a bit confusing as it's not clear if a server is expected to do something if it gets a value there (and it's also not clear what would cause a client like VS Code to send a specific value).

Along the same lines - I don't think it's really clear what `window/logMessage` is intended for. If clients to totally different things with it (eg. one writes to a file nobody sees, and the other writes to a visible output pane) it makes it hard for servers to use effectively.

**Comment by dbaeumer** [comment]
This happened for 3.16.
