### ISSUE TITLE
CompletionItem: Support multiple text edits

### ISSUE THREAD

**Issue by spoenemann** [Microsoft/language-server-protocol#11]
CompletionItem has a single TextEdit; it would be nice to allow multiple TextEdits.

Example: In the context of a Java file, the CompletionItem of a type (class, interface, etc.) could include an additional text edit to add an import declaration for that type if necessary.

**Comment by dbaeumer** [comment]
Good suggestion. 

@jrieken what do you think about this. We would need support in the vscode API for this as well.

**Comment by jrieken** [comment]
I like the idea but I am unsure if we should allow an array of edits or if we should allow a completion item to be a command (likely on top of an edit) that should run with the completion. That would enable the scenario above but also for more complex things, like adding a `dll` to the project or running a code action - like introduce member etc

**Comment by jrieken** [comment]
I have added https://github.com/Microsoft/vscode/issues/6874 for this

**Comment by mickaelistria** [comment]
Note that as a workaround, the returned TextEdit could be a full document change.

I believe it makes sense to have an "editor action" that can be any composition of TextEdit and Commands.

**Comment by kdvolder** [comment]
Just to add one more thought for consideration. The more complex an edit (or list of edits), the more time/cpu is probably spent computing it. The edits are typically only needed at the point of application not to display completions initially. In other words, typically you might show dozens of completions in the UI, but user ultimately only selects at most one of them for which the edits are then applied. 
So it would make sense to resolve the edits on demand. Is that already possible?

I'm okay with using the workaround to convert my 'complex list of edits' into something like a 'bulk-replace with cursor marker'. However I'd like to avoid computing that for all the completions ahead of time, especially if they all become 'full text replace' which means sending the entire contents of the editor over the wire for every single completion item.

I know there's already bits of the protocol that allow for 'resolving' completions, but this seems to be explained mostly for making the 'documentation' bits of a completion lazy computed. Its not clear to me from the LSP docs if that same resolve logic would/could also work for the edit in the completions.

**Comment by jrieken** [comment]
Yes - it should. From the VS Code side we *always* resolve an item when it is selected/focused and the LSP should then do the same

**Comment by kdvolder** [comment]
@jrieken That's probably good enough then. Too bad that its not possible to resolve docs / edit separately, so I guess edits will be resolved even if only the docs are needed and vice/versa.

**Comment by kdvolder** [comment]
Hmmm... workaround of doing 'full document replace with cursor marker' doesn't seem to be working.

I'm getting errors like these in the console my 'replace the whole document' completions are being ignored:

           INVALID text edit, must be single line and on the same line

Are completion edits limited in some way? Like... can't have newlines in them? Or 'must make changes only on the line where the cursor currently resides?

Or did I somehow misunderstand what is meant by 'full document change'? What I did was create a textedit who's range spans from the beginning to the end of the document and the new text is replacing that with all new text, including a `{{}}` to indicate where I want to put the cursor next.

**Comment by mickaelistria** [comment]
> `INVALID text edit, must be single line and on the same line`

Is this in VSCode? Did you try other Language Server Protocol clients?

**Comment by kdvolder** [comment]
> Is this in VSCode? Did you try other Language Server Protocol clients?

Yes. We are trying to develop some extensions for vscode using the language server protocol. Eventually we'd like to get those same extensions working with other protocol clients, but vscode is where the LSP came from and its the only thing what we are testing / developing with at the moment.

**Comment by kdvolder** [comment]
Could someone please clarify how to interpret the `INVALID text edit, must be single line and on the same line` message from VS code? 

E.g. I could imagine this to be interpreted in either of these two different ways, each suggesting a different type of follow up action to be taken:

1. this error is unintentional and not really part of the LSP spec. Follow up should be a bugreport to vscode to fix this and support completions with a single replace edit that spans multiple lines of text.

2. this error is intentional and should be considere part of the LSP Spec. Follow up action should be to amend the spec and clarify what restrictions apply here. Also this would raise the urgency of supporting multiple edits in the LSP as a single edit with these kinds of strict restrictions is too constraining for us to be able to implement the features we want in our 'language brain'.

**Comment by jrieken** [comment]
This error is generated [here](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/api/node/extHostLanguageFeatures.ts#L551), intentional, and means that your *main* text edit doesn't overlap with the cursor position

**Comment by kdvolder** [comment]
How can it not overlap the cursor if it covers the whole document? I.e. I was trying the suggested workaround of doing 'multiple edits' by doing a equivalent 'replace whole doc' edit. The cursor is in the document always... is it not? 

I question why we want to enforce any kind of limitations on the edits at all. I have some completion scenarios that need to insert text in another place than the cursor and move the cursor there. This is on purpose because my document structure demands certain contents to be inserted in a specific part of the document.

Putting limitations on this seems misguided, however, if you really must have limitation on what the LSP should consider an 'acceptable edit' these limitations should be clearly documented in the spec.

**Comment by dbaeumer** [comment]
I added support for additional text edits and commands to the protocol. Available in 2.6.0
