### ISSUE TITLE
Discrepancy in specification for `workspaceSymbolProvider`?

### ISSUE THREAD

**Issue by martskins** [microsoft/language-server-protocol#1109]
I'm not sure if I'm reading this wrong or if there's a discrepancy in the specification regarding `workspaceSymbolProvider`.

The field in the definition for `ServerCapabilities` states that `workspaceSymbolProvider` is an optional boolean, but under the specification for `Workspace Symbols Request` the server capability is defined like this:

```
Server Capability:

property path (optional): workspaceSymbolProvider
property type: boolean | WorkspaceSymbolOptions where WorkspaceSymbolOptions is defined as follows:
```

This was raised as an issue on LanguageClient-neovim as there is a python language server that is sending `WorkspaceSymbolOptions` in that field, but the client doesn't expect that type there. Is this a discrepancy in the documentation and the correct definition is the latter? Or is this an issue with the server instead?

**Comment by KamasamaK** [comment]
These discrepancies will occasionally come up because they were overlooked. Nothing ever gets removed unless it's a major release, so the one with more options is the proper one. If you look at the other versions, you'll see that `WorkspaceSymbolOptions` was added in v3.15. I just submitted PR #1105 for something similar to this. If you ever find something like this, you can just submit a PR.

**Comment by dbaeumer** [comment]
Good catch. This was an oversight when introducing progress reporting in 3.15. I simply forgot to update that property.

I updated 3.15 and 3.16 spec.
