### ISSUE TITLE
clarify codeAction/resolve spec

### ISSUE THREAD

**Issue by matklad** [microsoft/language-server-protocol#1136]
At the moment, `codeAction/resolve` dodges the question of "which fields, *exactly*, can be delayed":

>The request is sent from the client to the server to resolve additional information for a given code action. This is usually used to compute the edit property of a code action to avoid its unnecessary computation during the textDocument/codeAction request.

I think this is a rather unfortunate wording, because:

* client implementors won't know resolve of which fields they need to support
* for some fields, like `disabled`, it is effectively unimplementable, because it's impossible to distinguish between "`null`, because the value is `null`" and "`null`, because the value needs to be resolved". 

The VS Code side of the API gives much cleaner guarantees: 

>Given a code action fill in its edit-property. Changes to all other properties, like title, are ignored. A code action that has an edit will not be resolved.

**Comment by rwols** [comment]
Actually, shouldn't codeAction/resolve also be requested in case there's only an `edit` key? Because a code action can have both an `edit` as well as a `command`. The codeAction/resolve request could result in an extra `command` property filled in.

**Comment by matklad** [comment]
Yeah, this is also a grey area. I guess, the answer here today is "no, only edit can be resolved". But I think I might actually have a use-case for this, albeit a hacky one, to work-around #724

**Comment by matklad** [comment]
Ah, I see this is specified in the capability ("`properties`" list). It still unclear though how the client should distinguish between "property is `null`" vs "property needs to be resolved". I guess, the client can just always resolve `null` properties it knows about, and the server can return unchanged action for properties which actually are null, but that'd be extra round trips.

**Comment by rwols** [comment]
From what I understand: if a client has `"properties": ["edit", "command"]` in its capabilities, then:

```js
// 1: needs to be resolved, may potentially contain "edit" and "command" after resolve
{
    "title": "Do Foo"
}

// 2: needs to be resolved, may potentially contain an extra "command" after resolve
{
    "title": "Do Bar",
    "edit": []
}

// 3: needs to be resolved, may potentially contain an extra "edit" after resolve
{
    "title": "Do Baz",
    "command": {"command": "server/baz", "arguments": [1,2,3]}
}

// 4: no resolve needed
{
    "title": "Do Qux",
    "edit": [],
    "command": {"command": "server/qux", "arguments": [4,5,6]}
}
```

As it so happens, there are no keys in this CodeAction structure which can have the value `null`, so everything works out. But even then, only existence of keys should be checked I think. If a key exists then it is assumed to be the final value?

**Comment by dbaeumer** [comment]
@rwols nice explanation which is absolutely correct. I add something to the spec, but will not describe command support. It is not the intend of the resolve to compute a command lazily.

**Comment by testforstephen** [comment]
The latest fix declared that the client just supports lazy resolving the `edit` property, that's good. But it's still a little confusing about the case when the `codeAction/resolve` request will be requested.

If the code action response contains a command property, but no edit property, will it trigger `codeAction/resolve` request either?
```json
{
    "title": "Do Qux",
    "kind": "refactor",
    "command": {"command": "server/qux", "arguments": [4,5,6]}
}
```

At first I understood that as long as either the command or the edit is not null, it won't trigger lazy resolve because the command can handle and apply the edit itself. But after trying VS Code client, it only checks the edit property. If that's what the design does, it's better to clarify that the `codeAction/resolve` will be requested whenever the `edit` is null, regardless of the `command` property.

**Comment by rwols** [comment]
@testforstephen the key idea is that the client tells you what properties it will resolve via the

```
textDocument.codeAction.resolveSupport.properties
```

client capability. If `properties = ["edit"]` then the client will only resolve code actions which have a missing `edit` key.

> At first I understood that as long as either the command or the edit is not null, it won't trigger lazy resolve because the command can handle and apply the edit itself.

That's not true. It can be the case that *both* `edit` and `command` are present. Quoting from the spec:

```
/**
 * A code action represents a change that can be performed in code.
 * For example, to fix a problem or to refactor code.
 *
 * A CodeAction must set either `edit` and/or a `command`.
 * If both are supplied, the `edit` is applied first, then the `command`
 * is executed.
 */
```

Hence, if `textDocument.codeAction.resolveSupppprt.properties = ["edit"]`, and the client sees a code action with a `command` key but not an `edit` key, it must call `codeAction/resolve` because there could potentially be an `edit` key after the resolve.

**Comment by rwols** [comment]
So if you return code actions like this:

```js
{
    "title": "Do Qux",
    "kind": "refactor",
    "command": {"command": "server/qux", "arguments": [4,5,6]},
    "edit": []
}
```

a client with `textDocument.codeAction.resolveSupppprt.properties = ["edit"]` will *not* call `codeAction/resolve` because there's already an edit key (but without any real edits).

**Comment by testforstephen** [comment]
I see, thanks for the info. The fact is the `edit` is not a necessary property that must be included. For example, i have some code actions that need interactive UI to ask user info, we can use private commands for that, and we won't return the edit property. 

Given the resolveCodeAction capability cannot be applied per request. If I declare supporting it in the server side, then all code actions either returns an edit directly or lazy resolve it. This is not convenient and will force each request indirectly to include an edit property.

**Comment by dbaeumer** [comment]
I see the point but I think making this more configurable is not worth the effort compared to the gain. In completion items we have the same. What needs to be noted is that the resolve call should only be issued by clients before a code action is used (e.g. applied). So in the worst case this will result in another trip to the server which will not fill in the code action resolve property. As said the same happens for completion items if the user selects one in the list.
