### ISSUE TITLE
CompletionRegistrationOptions not included in server options

### ISSUE THREAD

**Issue by kjeremy** [microsoft/language-server-protocol#1143]
```ts
ServerCapabilities: {
  // ...
  completionProvider?: CompletionOptions;
  // ...
}
```

It looks like `CompletionRegistrationOptions` is not mentioned.

**Comment by dbaeumer** [comment]
This is on purpose to stay backwards compatible. The early 3.x version didn't have dynamic registration and hence adding `CompletionRegistrationOptions` would break existing clients. I would need to add a capability to guard this. But since having registration options only adds a small value (a id to unregister) I never spent the time to add this.
