### ISSUE TITLE
Declare protocol version

### ISSUE THREAD

**Issue by vladdu** [Microsoft/language-server-protocol#116]
Shouldn't the protocol version be declared somewhere when initialising the connection to the server? Maybe inside the ClientCapabilities and ServerCapabilities values? 

It's not a given that the server is always delivered together with the client, and it is possible that future versions of the protocol will confuse older clients or servers.

**Comment by dbaeumer** [comment]
Agree. Right no the assumption is made that an extension delivers the client and the server.

**Comment by vladdu** [comment]
I got a little confused -- why is there a 4.0 milestone but not a 3.0 one?

**Comment by dbaeumer** [comment]
There is a 3.0 implementation coming soon. But this one only fixes issues with the current protocol instead of adding new features. The 3.0 was meant to be a feature milestone which might even be breaking. Hence I renamed it to 4.0.

This being said I added capability flags to the 3.0 version in a compatible way. I choose capability flags instead of protocol version since it makes things more explicit from a client side. You might want to have a look here: https://github.com/Microsoft/language-server-protocol/blob/master/protocol.md#initialize-request with the new ClientCapabilities. 

Setting to January since it will come soon.

**Comment by vladdu** [comment]
I see. Then I think it should be specified that all messages may include extra keys, and for compability unknown ones should be ignored. There are implementations that compile the spec to code, an these need to be able to handle data they don't recognise.

**Comment by dbaeumer** [comment]
Clarified in the protocol spec.
