### ISSUE TITLE
clarify usage of request IDs

### ISSUE THREAD

**Issue by vladdu** [Microsoft/language-server-protocol#118]
Can IDs be any string? Or only a string representation of a number? 

Is the only constraint that there should not be two concurrent requests with the same ID? Or do they have to be consecutive (if quasi-numerical)?

If a request is received wit the same ID as a pending one, is InvalidRequest the proper error code?

Are the server->client and client->server IDs independent? I.e. can we have the same ID for two simultaneous requesta?

**Comment by felixfbecker** [comment]
This is not defined by the LSP but by JSON RPC spec:
http://www.jsonrpc.org/specification#request_object
> id
> An identifier established by the Client that MUST contain a String, Number, or NULL value if included. If it is not included it is assumed to be a notification. The value SHOULD normally not be Null [1] and Numbers SHOULD NOT contain fractional parts [2]

http://www.jsonrpc.org/specification#response_object

> id
> This member is REQUIRED.
> It MUST be the same as the value of the id member in the Request Object.
If there was an error in detecting the id in the Request object (e.g. Parse error/Invalid Request), it MUST be Null.

I assume string is allowed for `id` to allow the usage of UUIDs instead of sequential numbers.

**Comment by vladdu** [comment]
You are right, I got confused by the fact that the descriptions of the data structures includes the base JSON-RPC ones.

**Comment by bruno-medeiros** [comment]
I'd say there are some aspects that could still be clarified in LSP, because LSP can always specify additional guarantees over what JSON-RPC specifies. 

For example JSON-RPC does not require the id to be unique, but I imagine it has to be so in LSP, otherwise the Cancel Request could not work properly. Nor could you even properly match received responses to their originating request (unless a 100% synchronous behaviour was used, which is not the case for LSP).

And yeah, I think the server->client and client->server IDs namespaces are independent.

**Comment by dbaeumer** [comment]
@bruno-medeiros agree that this can be further clarified and a PR that clarifies it is welcome.
