### ISSUE TITLE
How are the startCharacter and endCharacter properties on folding ranges defined?

### ISSUE THREAD

**Issue by Darkgaja** [microsoft/language-server-protocol#1198]
We are currently in the process of implementing folding support for Xtext. (https://github.com/eclipse/xtext-core/pull/1672)

There has been some discussion regarding the use of the `startCharacter` and `endCharacter` properties of the FoldingRange. It's not quite clear how exactly these are defined. Especially since I couldn't find any reference implementation and vscode only uses line based folding, so I couldn't test it either.

Could someone please give some clarification on how these are defined? An actual example would be highly appreciated.

**Comment by dbaeumer** [comment]
@aeschli can you please clarify. Thanks!

**Comment by aeschli** [comment]
startLine/startCharacter - endLine/endCharacter define a Range. That's the range that is hidden when that folding range is collapsed.

**Comment by Darkgaja** [comment]
@aeschli Right, I think my question wasn't clear enough: Are the `startCharacter` and `endCharacter` properties indices of the full document string or are they defined as the column of the `startLine`/`endLine`?

**Comment by KamasamaK** [comment]
Based on them defaulting to the length of the relevant line, it should be the column of the line. However, it's not clear why `startCharacter` would default to the length of the start line. I would have expected it to default to `0`.

**Comment by aeschli** [comment]
Yes, character is the offset in the line. In LSP all positions are line/character (like line/column except that columns typically start with 1, while characters start with 0)
In editors that only support folding full lines (such as VSCode), the line at `startLine` gets the folding marker, but when folded, is still fully visible.

![image](https://user-images.githubusercontent.com/6461412/109774227-6918a880-7c00-11eb-8329-b771f3edfdcb.png)

You can say it folds after the last character of the first line. That's why the comment says: `defaults to the length of the line`

**Comment by Darkgaja** [comment]
I see, thank you for your explanation. I will close this issue.
