### ISSUE TITLE
Clarify JSON message separator

### ISSUE THREAD

**Issue by jonathandturner** [Microsoft/language-server-protocol#127]
Hey all -

We were working on the Rust LS and there were some questions about possibly using a \n between the JSON messages.  I took a peak at http://www.jsonrpc.org/specification but nothing jumped out at me as this being allowed or disallowed.

Can you help clarify whether or not a carriage return between JSON messages is allowed?

**Comment by dbaeumer** [comment]
@jonathandturner JSON-rpc doesn't specify how messages are transported. The transport is currently speced in the LSP but discussions in other issues showed that this has to me moved out of the LSP specification. Nevertheless it must be specified since client and server must speak the same transport. Currently the transport is specified using a header and a content part with a length encoding. This is documented here: https://github.com/Microsoft/language-server-protocol/blob/master/protocol.md#base-protocol

What is the reason that you want to use \n between the messages.

**Comment by jonathandturner** [comment]
I wouldn't say this is a big issue, but some people working with the Rust LS thought it would help readability when you're trying to build the tools.

That said, what we really weren't sure about was what the spec said about it.  Like you say, both server and client have to agree.  We want the RLS to ultimately follow the spec as closely as we can, so we work with as many tools as possible.

**Comment by bruno-medeiros** [comment]
@jonathandturner I think can be made strictly compliant if you include the '\r\n' as part of the content, for example:

```
Content-Length: 5\r\n
\r\n
{ }\r\n
```

The content will then be `{ }\r\n` which should be fine in terms of JSON parsing since it's just extra whitespace.

If on the hand, you specify the content to just be `{ }` , the `\r\n` will be left hanging, and will be included in the [Header Part](https://github.com/Microsoft/language-server-protocol/blob/master/protocol.md#header-part). The header part is made of header fields though, and it requires at least one header field. So if an  `\r\n` line is encountered straight away, that would be an error, even if an easily recoverable one (ignore the line). Either way no need to be confusing the client.

**Comment by matklad** [comment]
To paraphrase this a bit more formally, what are whitespace requirements for the content part? Are trailing/leading whitespace allowed? Are internal `\n` allowed? I would say that the whitespace does not matter, because LSP uses JSON-RPC, which uses JSON, which says that whitespace is insignificant.

There is an orthogonal option to require (or recommend, or forbid, or not specify) that server messages always include trailing `\n` and never uses internal `\n` (while not restricting client messages). This may make client implementation easier, because than you can frame messages based on new lines, and not on the content lengths, and it might be the case that newline framing is easier or build in for a particular client.

**Comment by bruno-medeiros** [comment]
Whoa, restricting the content part to not include `\n`?... That seems like a step too far.

@matklad What language/context do you have in mind, out of curiosity? Parsing the Content-Length headers and the content-part in a conformant way seems like a trivial task in any language... just a few lines of code.

**Comment by dbaeumer** [comment]
I will close this one in favor of https://github.com/Microsoft/language-server-protocol/issues/86#issuecomment-257272415. I agree that the actual transport should not be part of the LSP specification and that we instead should specify n different transports where one or two are mandatory.
