### ISSUE TITLE
How should a server handle a missing or extra id?

### ISSUE THREAD

**Issue by michaelmesser** [microsoft/language-server-protocol#1278]
How should a server respond in the following situations?
1. The method of a message is a notification and the message has an id
2. The method of a message is a request and the message does not have an id

**Comment by dbaeumer** [comment]
1.) An id clearly defines a message as a request. So I would return an error with an ID https://github.com/microsoft/vscode-languageserver-node/blob/main/jsonrpc/src/common/messages.ts#L43 since no request message exist.

2.) this is harder since no error can be reported back. All that can be done is to log this and report it back to the client in the log.
