### ISSUE TITLE
Make CodeLenses more generic

### ISSUE THREAD

**Issue by vladdu** [Microsoft/language-server-protocol#128]
CodeLenses allow registering actions to elements (ranges) in the code. The specification is currently very VSCode specific, in that the commands are supposed to be displayed in-line with the code in a magic text line, a feature that not many other clients have (if any). Another way of implementing these would be to show the information on the context menu, but this would make the VSCode editor unwieldy (actually, useless is a better description), if every symbol can have their own lens.

The backwards compatible implementation would be to either have a separate request, or add a flag to the existing lenses (marking each item as "normal", "menu" or both). 

[edit] I think a new request is better, because it can be sent when needed instead of when opening the document. It can then be context-sensitive.

**Comment by dbaeumer** [comment]
To keep the number of issues in our inbox at a manageable level, we’re closing issues that have been on the backlog for a long time but haven’t gained traction: we look at the number of votes the issue has received and the number of duplicate issues filed. Thank you for your time and understanding.

If you disagree and feel that this issue is crucial: we’re happy to listen and to reconsider.
