### ISSUE TITLE
clarify response in case of cancellation of request

### ISSUE THREAD

**Issue by vladdu** [Microsoft/language-server-protocol#133]
If a request is cancelled, it is not specified what the answer may be, in case the server can't return a partial result. The protocol allows both `result`  and `error` to be absent (or null), and at least VSCode seems to handle `null` results gracefully but I think it should be stated clearly what is to be expected.

**Comment by dbaeumer** [comment]
This is part of the doc:

A request that got canceled still needs to return from the server and send a response back. It can not be left open / hanging. This is in line with the JSON RPC protocol that requires that every request sends a response back. In addition it allows for returning partial results on cancel.

Since the client knows that a request got canceled it can decide what it does with the result if present and an error if presented.

Please ping if I misunderstood something.
