### ISSUE TITLE
workspace/symbol request does not include the workspace uri

### ISSUE THREAD

**Issue by Scaremonger** [microsoft/language-server-protocol#1383]
Hi,
When a language server is managing multiple workspaces; the workspace/symbol message is impossible to process because it does not contain any uri forcing you to return all symbols in all open workspaces:
```
{
  "id": 9,
  "jsonrpc": "2.0",
  "method": "workspace/symbol",
  "params": {
    "query": "que"
  }
}
```
The above example shows a simple request with a query, but does not indicate which workspace to use.

**Comment by dbaeumer** [comment]
The LSP protocol has not support for multi tenant / multi workspace right now. Adding this is a bigger effort and needs more work than having a URI in the workspace symbol request. 

I will close the issue since add multi tenant / multi workspace support is currently not in scope for LSP. 

However we try to not add things that make it harder in the future.
