### ISSUE TITLE
Consider making format request return `TextDocumentEdit` instead `TextEdit[]` 

### ISSUE THREAD

**Issue by masad-frost** [microsoft/language-server-protocol#1385]
When sending a format request the result is an array of `TextEdit`. This response doesn't tell us which version of the document the formatting happened on, meaning if we were to apply those edits, we wouldn't know to transform those edits with respect to local changes since X version. Not accurately at least, one could store the version in local scope on the client before firing off the request but there's no guarantee on which version the server will be running the formatter on, the protocol does not specify handling all the sent `textDocument/didChange` before the format request.

**Comment by dbaeumer** [comment]
The specification states that these requests are made on the latest sync version of the document. So a client needs to take care of the fact that it either ignores the result if the content has changed in the meantime on the client side or it needs to adjust the result if possible.

I will close the issue since this is how LSP works for other requests as well.
