### ISSUE TITLE
Please explain the concept of absence of a capability at initialization

### ISSUE THREAD

**Issue by przepompownia** [microsoft/language-server-protocol#1403]
> A missing property should be interpreted as an absence of the capability. 

Suppose both a server and a client have implemented support of `textDocument/references` and the client at initialization sends no `textDocument.references` field (say, by the user choice). Should `capabilities.referencesProvider` be then empty in `ServerCapabilities`?

**Comment by dbaeumer** [comment]
@przepompownia `capabilities.referencesProvider` should be empty. If the server fills it in the client will ignore it since it signaled no support for references.

The recommended way is a that a server doesn't set up providers for capabilities not supported by the client to use less system resources.

**Comment by przepompownia** [comment]
Thanks!
