### ISSUE TITLE
The navigator of the document is broken.

### ISSUE THREAD

**Issue by vincentdchan** [microsoft/language-server-protocol#1420]
Page: [https://microsoft.github.io/language-server-protocol/specification](https://microsoft.github.io/language-server-protocol/specification)

The link in the navigator on the right of the page refer to `#diagnostics-side`, this is a wrong link.
Actually it's `#diagnostics`.

**Comment by dbaeumer** [comment]
@vincentdchan this is done by the side generator. The `Diagnostics` entry is actually not navigatable since clicking on it expands / collapse the note. I do set the right anchor though (see https://github.com/microsoft/language-server-protocol/blob/539c919cbc3b2d8c5c9e08ab27d883a6772c3d80/_data/specification-3-16-toc.yml#L158).

I am not a deep expert of bootstrap. So I don't know if this can be changed. Does anyone else know?

**Comment by vincentdchan** [comment]
I think the `anchor` field should be `diagnostics-side`?
What side generator are you using?

**Comment by dbaeumer** [comment]
The default GitHub which is Jekyll together with bootstrap.

**Comment by dbaeumer** [comment]
I will close the issue since this got addressed with the restructuring of the documents.
