### ISSUE TITLE
Support Inline Completions

### ISSUE THREAD

**Issue by KamasamaK** [microsoft/language-server-protocol#1529]
The [Inline Completions API](https://github.com/microsoft/vscode/issues/124024) has been finalized in VS Code, so support should be added to the LSP.

**Comment by c-claeys** [comment]
This is in the backlog, are you open to PRs for this? The public VSCode API provides a clear path, in my opinion. Happy to send PRs here for the spec and https://github.com/microsoft/vscode-languageserver-node

**Comment by mroch** [comment]
Meta is also interested in helping push this forward! How can we help?

**Comment by bolinfest** [comment]
@dbaeumer In implementing this in our LSP, we are finding the need to throttle these events, wait to see if a cancellation is sent, etc. As such, it would be helpful to formalize the LSP request so it takes a `VersionedTextDocumentIdentifier` (or perhaps to be more flexible, an `OptionalVersionedTextDocumentIdentifier`) rather than a plain `TextDocumentIdentifier` so that by the time the inline completions request is handled, it can verify that the version of the document it has in memory matches the one that was specified in the inline completions request (as text document update events may have been processed inbetween).

**Comment by dbaeumer** [comment]
PRs are welcome. But they have to be made for `vscode-languageserver-node` (or another implementation) as well.

**Comment by dbaeumer** [comment]
@bolinfest IMO this is not necessary since the ordering in which requests and notifications are sent to the server guarantees that a request is always on the latest updated document state the client has sent. If a server reorders these (which he is allowed to do) then the server needs to keep track of the versions the reordering has happened.

**Comment by bolinfest** [comment]
@dbaeumer Another request (which is perhaps strictly spec-related) is that I see that [`ErrorCodes.ServerCancelled`](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#responseMessage) has the following caveat:

```
/**
 * The server cancelled the request. This error code should
 * only be used for requests that explicitly support being
 * server cancellable.
 *
 * @since 3.17.0
 */
 ```
 
 Could we formally declare that inline completions are server cancellable?

**Comment by dbaeumer** [comment]
No, we can't since this is client specific. There is a `serverCancelSupport` capability for those requests that support this. To my knowledge VS Code doesn't have cancel support (that retriggers the request) for inline completion. It does for semantic tokens.

**Comment by dbaeumer** [comment]
This got added as proposed for 3.18.
