### ISSUE TITLE
DocumentDiagnosticReportKind does not exist on meta model

### ISSUE THREAD

**Issue by mtsmfm** [microsoft/language-server-protocol#1541]
It exists on https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/ but I can't find it on https://github.com/microsoft/language-server-protocol/blob/7e7971fca4ceeab1078374e2d331c5d21278da99/_specifications/lsp/3.17/metaModel/metaModel.json.

Is this intentional?

**Comment by dbaeumer** [comment]
Fixed.

**Comment by dbaeumer** [comment]
Fixed in node repository. Still needs to move the meta model to the web site.

**Comment by mtsmfm** [comment]
📝 https://github.com/microsoft/vscode-languageserver-node/pull/1071

**Comment by paracycle** [comment]
> Fixed in node repository. Still needs to move the meta model to the web site.

@dbaeumer Is the node repository the main source of truth for the meta model? The reason this came up is because I was trying to [refactor](https://github.com/mtsmfm/language_server-protocol-ruby/pull/37) the [Ruby LSP SDK](https://github.com/mtsmfm/language_server-protocol-ruby) to use the meta model instead of the TS code to generate Ruby classes and this type ended up [being missed](https://github.com/mtsmfm/language_server-protocol-ruby/pull/49#discussion_r960943392).

I would like to point to the meta model definition on the node repository if that is the location that is better maintained.

**Comment by dbaeumer** [comment]
The meta model in the node repository is the one I maintain. The one here is always a copy of that one. Let me update it.

**Comment by dbaeumer** [comment]
See https://github.com/microsoft/language-server-protocol/pull/1549
