### ISSUE TITLE
Why is the protocol spec now using namespaces with consts instead of enums?

### ISSUE THREAD

**Issue by felixfbecker** [Microsoft/language-server-protocol#161]
This was the 2.0 spec for `CompletionKind`:
```ts
/**
 * The kind of a completion entry.
 */
enum CompletionItemKind {
    Text = 1,
    Method = 2,
    Function = 3,
    Constructor = 4,
    Field = 5,
    Variable = 6,
    Class = 7,
    Interface = 8,
    Module = 9,
    Property = 10,
    Unit = 11,
    Value = 12,
    Enum = 13,
    Keyword = 14,
    Snippet = 15,
    Color = 16,
    File = 17,
    Reference = 18
}
```

This is the newest spec for `CompletionKind`:
```ts
/**
 * The kind of a completion entry.
 */
namespace CompletionItemKind {
    export const Text = 1;
    export const Method = 2;
    export const Function = 3;
    export const Constructor = 4;
    export const Field = 5;
    export const Variable = 6;
    export const Class = 7;
    export const Interface = 8;
    export const Module = 9;
    export const Property = 10;
    export const Unit = 11;
    export const Value = 12;
    export const Enum = 13;
    export const Keyword = 14;
    export const Snippet = 15;
    export const Color = 16;
    export const File = 17;
    export const Reference = 18;
}
```

The former is less verbose, easy to understand for developers of any language and also the terminology of JSON schema. The latter also breaks TypeScript naming conventions - variables should be camelCased, constants may be SNAKE_CASED. PascalCase is only used for classes and enum members.

Is there a reason this was changed?

**Comment by bruno-medeiros** [comment]
I suspect it is to allow languages to specify language-specific extensions, since this is a very language-specific functionality (unlike most of LSP).  Take D for example: https://github.com/DDT-IDE/DDT/blob/master/plugin_tooling/src/melnorme/lang/tooling/CompletionProposalKind.java , there's lots of kinds there that are not represented in the standard LSP kinds. Or for example your own: https://github.com/Microsoft/language-server-protocol/issues/158

I suspect it would be hard for LSP to try to catch up to all the possible combinations in all languages, and would put an extra burden on client implementation. (for example, to provide an icon for all possible kinds?) Or at least it would take time, since any new update could only come in next version of LSP.

**Comment by felixfbecker** [comment]
@bruno-medeiros Well the only way the kind is useful is for displaying an icon (since it is just a number). There would be no point in reportin a not-speced kind, the client wouldn't know what to do with it. Which is why I currently report traits as classes, and maybe D should report Tuple as Value.

How does an enum prevent extending it though? You just showed an example of someone extending it by using an enum, not a namespace with constants

**Comment by bruno-medeiros** [comment]
> How does an enum prevent extending it though? 

I would say so: an enum is only allowed to have those predefined values. If CompletionItemKind is specified as an enum, one could still override the LSP serialization mechanism to serialize/deserialize CompletionItemKind  to a different *type* if it is a non-standard kind, but that makes things more complicated, especially if using a library to automatically serialize/deserialize JSON into types (which seems to be the more common). 
On the other hand, if CompletionItemKind if specified as an integer (with some predefined constants), it makes it simpler to handle with automatic serialization/deserialization.

That is my understanding, but I'll leave it to the project devs to confirm.

>You just showed an example of someone extending it by using an enum, not a namespace with constants

I did what? You mean https://github.com/DDT-IDE/DDT/blob/master/plugin_tooling/src/melnorme/lang/tooling/CompletionProposalKind.java ? That code/IDE doesn't use LSP at all, I just showed that enum to point out some different item kinds in D language, that have no match in LSP.

**Comment by felixfbecker** [comment]
Sure, but nothing prevents the implementing language server from simply defining its `CompletionItemKind` enum with a special custom member (maybe with a very high value to avoid conflicts), just like you would define an extra exported constant in the namespace. Some languages even support extending enums. Some languages don't support enums at all (some don't support namespaces). Using namespaces or enums here makes no difference, except in the points I mentioned in the OP

**Comment by wiz** [comment]
> variables should be camelCased, constants may be SNAKE_CASED. PascalCase is only used for classes and enum members.

and then, there is
```
    export const unknownProtocolVersion: number = 1;
```

**Comment by dbaeumer** [comment]
The protocol specification always used numbers in the spec, never enums (since the protocol itself can not assume that the implementing language has support for enums). So the `kind` attribute in `CompletionItem` was always speced as:

export interface CompletionItem {
	/**
	 * The kind of this completion item. Based of the kind
	 * an icon is chosen by the editor.
	 */
	kind?: number;
}

Then there was an enum definition listing the values. This confused people since there was no obvious relationship between the kind?: number and the enum and some thought that the implementation language needs to support enums. That is why we decided to declare them as numbers in namespace instead of enum (we could have chosen global const values as well). The functionality itself stayed the same. 

In the protocol.d.ts itself (which represents the node implementation of the spec) we even went a step further and now have:

```ts
/**
 * The kind of a completion entry.
 */
export namespace CompletionItemKind {
	export const Text: 1 = 1;
	export const Method: 2 = 2;
	export const Function: 3 = 3;
	export const Constructor: 4 = 4;
	export const Field: 5 = 5;
	export const Variable: 6 = 6;
	export const Class: 7 = 7;
	export const Interface: 8 = 8;
	export const Module: 9 = 9;
	export const Property: 10 = 10;
	export const Unit: 11 = 11;
	export const Value: 12 = 12;
	export const Enum: 13 = 13;
	export const Keyword: 14 = 14;
	export const Snippet: 15 = 15;
	export const Color: 16 = 16;
	export const File: 17 = 17;
	export const Reference: 18 = 18;
}

export type CompletionItemKind = 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10 | 11 | 12 | 13 | 14 | 15 | 16 | 17 | 18;

export interface CompletionItem {
	/**
	 * The kind of this completion item. Based of the kind
	 * an icon is chosen by the editor.
	 */
	kind?: CompletionItemKind;
}
```ts

This besides more clarify improved compiler checking.

The major driver here was not extensibility, it was more about making it clear that the protocol itself relies in numbers and not enums.

@wiz: good catch. I will rename the constant. 

Any objection to close this since this change didn't change the protocol in any way. We did it to improve understandability.

**Comment by felixfbecker** [comment]
Thanks a lot @dbaeumer for the explanation! Personally I find it more confusing this way than with enums, since an enum is a number, nothing prevents anyone from extending them and you should code your implementation to handle unknown values in any case. But if other users think differently then I see where you're coming from.

The only question left is how this will be converted if you switch to JSON schema.
