### ISSUE TITLE
Where can I find more documentation on VSCode's LSP configurations and settings?

### ISSUE THREAD

**Issue by kernelguardian** [microsoft/language-server-protocol#1631]
I have been tinkering with the VSCode's Language Server Protocol for a while now. I really would like to learn more. However I couldn't find much resources. Right now I am trying to find the documentation for this part of code

transport: TransportKind.ipc 

from [here](https://code.visualstudio.com/api/language-extensions/language-server-extension-guide#advanced-topics). What if I need to find other forms of transport communication like stdio or something else. What other communication options are there and possible examples. Where can I find these?

**Comment by dbaeumer** [comment]
The transport kinds are not part of the spec since they depend on the environment in which you use LSP (for example they are completely different in a browser environment). But there are implementation considerations for the desktop here: https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#implementationConsiderations

**Comment by kernelguardian** [comment]
Thanks
