### ISSUE TITLE
Identifying the content type for progress parameters

### ISSUE THREAD

**Issue by rhdunn** [microsoft/language-server-protocol#1633]
I'm thinking on how to implement [Progress Support](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#progress) handlers. Looking at that part of the specifications, the `data` is either:
1. A work done progress event, where the objects have a `kind` type to disambiguate what type it is;
2. A partial result event.

For partial results, the type is dependent on the specific event as documented throughout the specification. This means (from my understanding) that the client needs to store a map of progress tokens to request methods, then use that to check and decode the `data` field of the progress parameters.

This makes it more complex to implement in static programming languages.

It would be better if the method associated with the progress was included in the progress results.

Alternatively, it would be helpful for implementors to have a section of guidance on how to handle/implement partial result event handlers.

**Comment by dbaeumer** [comment]
> It would be better if the method associated with the progress was included in the progress results.

I think that would make it more complex since there can be two requests for the same method running in parallel. This is why the client can provide a special token. I stayed away from the message ID as the token since it would make it hard to use LSP over something that doesn't have that ID. In addition you would have a map from method name to progress then.

In general I stay away from advising how clients should implement this in a library since it highly depends on what features the implementation language provides. You could for example have a special promise with a progress callback, a progress token you pass in with an event or a special even callback as I did in the JSONRPC library (see https://github.com/microsoft/vscode-languageserver-node/blob/3d536d7a08c0555f1ca3f2a70b1d5783e1adbfa1/protocol/src/node/test/connection.test.ts#L120)

Let me know if this makes sense.

**Comment by rhdunn** [comment]
Thanks. That makes sense.

I'm implementing an LSP API and server in Kotlin. I need to think more on how to handle this properly.

**Comment by dbaeumer** [comment]
Thanks for reaching back. I will close the issue then.
