### ISSUE TITLE
`CompletionList.itemDefaults` overriding behavior

### ISSUE THREAD

**Issue by rchl** [microsoft/language-server-protocol#1660]
The description of the `CompletionList.itemDefaults` states:

```ts
	/**
	 * In many cases the items of an actual completion result share the same
	 * value for properties like `commitCharacters` or the range of a text
	 * edit. A completion list can therefore define item defaults which will
	 * be used if a completion item itself doesn't specify the value.
	 *
	 * If a completion list specifies a default value and a completion item
	 * also specifies a corresponding value the one from the item is used.
	 *
	 * Servers are only allowed to return default values if the client
	 * signals support for this via the `completionList.itemDefaults`
	 * capability.
	 *
	 * @since 3.17.0
	 */
```

It's not clear to me what happens when `itemDefaults` includes, for example, a `commitCharacters` property and the `CompletionItem` explicitly sets `commitCharacters` to `undefined`. Does the resolved value for that completion item is the value from `itemDefaults` or is it to be treated as not set?

I'm guessing that `undefined` should be treated the same as "not set" so the `itemDefaults` value should win because not all languages can differentiate between `undefined` and unset. But in that case I suppose we end up with a potential issue that it's not possible to `unset` a value that is defined in `itemDefaults`... (might not necessarily be a problem for `commitCharacters` since it could be set to an empty list but it could be an issue for other cases).

**Comment by dbaeumer** [comment]
If a server set `commitCharacters` to `undefined` the client will receive a literal with the property not set. Reason is that JSON has no support for sending a `undefined` value. It can only omit values. This is why the specification defines it as `commitCharacters?: string[];` which in TS is slightly different than `commitCharacters: string[] | undefined;`

I will close the issue since this is how JSON works and is nothing LSP can influence.

**Comment by rchl** [comment]
In that case, this can be an issue:

> we end up with a potential issue that it's not possible to `unset` a value that is defined in `itemDefaults`... (might not necessarily be a problem for `commitCharacters` since it could be set to an empty list but it could be an issue for other cases).

(I have only done some preliminary investigation towards implementing `itemDefaults` in one server so I'm not sure if it would be an issue in practice.)

**Comment by jimmylewis** [comment]
We have some servers using this pattern and it does require that if you set `itemDefaults` you will need to set `commitCharacters` for any completion item not using those defaults.  This might mean that a completion item which previously omitted `commitCharacters` (e.g. because it relied on the defaults from the server capability) may need to now specify them if `itemDefaults` is set to a different set of commit characters on this response.  It's been pretty manageable in practice and was a significant performance boost regarding serialization overhead in some cases (instead of serializing `commitCharacters` on thousands of individual completion items, we do it once in the `itemDefaults` and only a few times on individual items as needed).

**Comment by rchl** [comment]
Yes though it depends on the payload. It can actually make the payload bigger if most of the completions don't come with `commitCharacters` by default. And adding some pre-processing for each payload to figure out whether setting `itemDefaults` would improve things or not might defeat the purpose.

But I suppose it might not make sense to be able to override completion property to be "unset" as, however it would look like, it would probably take same amount of bytes or more as it takes to just set it to a default value.
