### ISSUE TITLE
Regarding the type of `ResponseMessage#result`

### ISSUE THREAD

**Issue by reflectronic** [microsoft/language-server-protocol#1729]
`ResponseMessage` is defined like this:
```ts
interface ResponseMessage extends Message {
        // ...
	result?: string | number | boolean | array | object | null;
        // ...
}
```

(`ResponseError#data` has the same type as above.) 

I am writing a code generator for LSP and this case is a little unpleasant to handle.  I already handle `LSPAny` specially, but handling this disjunction in addition to that adds complexity to my tool.

I am not sure what the difference between `string | number | boolean | array | object | null` and `LSPAny` is. If there isn't one, it would make my tool simpler to just replace it with `LSPAny`. If there is one, please let me know.

**Comment by dbaeumer** [comment]
This is due to layering since the `jsonrpc` package is independent of the LSP stack (it is used outside LSP as well). In TypeScript typing wise it all boils down to the same base types. However this might not be true for other languages. For example result uses `number` whereas LSP uses `integer` | `uinteger` to define a more strict value range.
