### ISSUE TITLE
Include LSP version in InitializeResult

### ISSUE THREAD

**Issue by ljw1004** [Microsoft/language-server-protocol#174]
Please include the LSP version inside InitializeResult.

Context: I had just got started with LSP, and was experimenting by sending messages to `pyls`. I wasted a lot of time because I was trying to send LSPv3 stuff to it, but it only understood LSPv2.

You might think this would be obvious, but it wasn't! Javascript/JSON tradition is to be pretty loosey-goosey about what you accept and emit, rather than adhering to the letter of the protocol. So when I sent a `rootUri` parameter in Initialize, the language server just silently ignored it rather than trumpeting the fact that it doesn't recognize it. (and so subsequent operations failed with confusing messages).

I could have solved this problem by reading the pyls documentation more carefully.

But I'd rather just have it be self-documenting in the InitializeResult message.

**Comment by dbaeumer** [comment]
We had a long debate over this and decided to go with capabilities instead of version numbers. Therefore a client announces its capabilities in the initialize request and the server announces its capabilities in the initialize response. Even if a server support protocol x it doesn't means it provides all features defined in protocol x. It is free to support only a subset.

Did you check the initialize response for this? Or was there a breakage in the protocol (the JSOn structure) itself which we try to avoid as mush as possible.

**Comment by dbaeumer** [comment]
I see the problem with the rootPath. But a version number wouldn't have helped here either since the rootPath is sent on initialize request. At the end the pyls server should have responed with an error from the initialize request if the rootPath property is missing but is mandatory for him to work.

**Comment by ljw1004** [comment]
Okay, fair enough. Feel free to close.

The situation I think of is: (1) I initiate a request, (2) it sends back capabilities, (3) I try to understand how exactly to use those capabilities. But I can't make sense of the capabilities unless I know which spec document to read from.

**Comment by dbaeumer** [comment]
If we break things or add things that aren't compatible we announce them in the capabilities. This is basically a version per request/response. An example is the snippet support in completion item. The client announces that it supports snippets which requires additional properties on the CompletionItem. Now a server that talks to a client not handling snippets needs to filter them out or in the worst case doesn't provide completion support to such a client.
