### ISSUE TITLE
Clarify relationship between rootUri/rootPath, and TextDocumenItem:uri

### ISSUE THREAD

**Issue by ljw1004** [Microsoft/language-server-protocol#176]
In Initialize request, we send either `rootUri` or `rootPath`. In TextDocumentItem, we send a document's `uri`.

What exactly is the relationship between this `uri`, and the `rootUri/rootPath`? 

Experimentally, I determined that the Python language server pyls requires that `rootPath` be a string prefix of `uri` -- if not it returns a {Internal Error} response code. That feels a bit fishy... I didn't think that "string prefix" is one of the standard defined operations upon URIs. It's also fishy to be comparing "Path" with "URI", even though they seem like two different concepts.

I'd like to see protocol.md itself specify what is the expected relationship between rootPath and document URI.

**Comment by ljw1004** [comment]
See also #27

**Comment by dbaeumer** [comment]
`rootPath` got deprecated in favour of `rootUri`. Reason being that the whole protocol talks about URIs and only the root was a file path. That was a mistake in the design of the protocol.

The root Uri basically determines the workspace you have open. In 99% of the cases documents will be inside that workspace but there is no enforcement of this and a language server should handle documents outside the root gracefully. All language servers developed by the VS Code team do so. If we receive a document (for example a json file) from outside the workspace we still provide basic language features for them but can't respect any workspace specific setting since we can't load any.

At the end it is up to the implementer of the LS to handle this correctly.

Regarding #27: this is why I still think that URI shouldn't be relative to a workspace folder. You can (a) open a single file and (b) navigate to a different file outside the workspace (for example in C where system header files are stored globally).

**Comment by ljw1004** [comment]
There are two issues:

(1) Imagine if rootUri is `file:///dir`. And then you send a document-open request for either `file://localhost/dir/a.txt` or `file:///dir/a.txt`. Both are equivalent URIs, pointing to exactly the same resource, and that resource is within the rootUri. But pyls behavior would be to reject the first and accept the second. I think protocol.md should make clear that both URIs should be treated the same.

(2) I think your C++ header example is compelling, and it applies to other languages like pyls. I think that protocol.md should put this expectation in a note, so I can point the pyls team to this expectation.

**Comment by dbaeumer** [comment]
@ljw1004 are you willing to provide a PR. For (1) I think this is something the client should ensure. A file should always be addressed using the same URI. URI equality is hard and IMO only possible when you resolve it.
