### ISSUE TITLE
a notify can validate server is ready

### ISSUE THREAD

**Issue by glepnir** [microsoft/language-server-protocol#1764]
Provide a notify to verify that the server is ready. Some servers have their own implementations. It would be more useful to provide a standard implementation, progress messages are like a catch-up game. Unable to verify the status of the server.

I think this should be brought up ？ But I didn't find absolutely related issues.

**Comment by dbaeumer** [comment]
I am not sure what this should bring since all the communication is already async. A server for example can not return from `initialize` until it is ready or the client can wait for existing requests until a server can fullfil them. Having an explicit ready even will IMO not bring additional fleibility.

**Comment by dbaeumer** [comment]
The feature has not gain any traction in the community. I therefore close the issue. Still a big Thank You to you for taking the time to create this issue! To learn more about how we handle feature requests, please see our [documentation](https://aka.ms/vscode-issue-lifecycle).

Happy Coding!
