### ISSUE TITLE
No registration options documentation on dynamic registration for workspace/didChangeConfiguration

### ISSUE THREAD

**Issue by lukaszsamson** [microsoft/language-server-protocol#1792]
The documentation in https://microsoft.github.io/language-server-protocol/specifications/lsp/3.18/specification/#workspace_didChangeConfiguration does not state what is the schema for registration options. When I pass an empty map, VSCode emits notifications with `null`

```
[Trace - 14:06:50] Sending notification 'workspace/didChangeConfiguration'.
Params: {
    "settings": null
}
```
To make it work it seems VSCode (as of 1.81.1) needs
```
{
  "scopeUri": string,
  "section": string
}
```
similar to what 'workspace/configuration' request expects.
Edit:
this seems the schema used by VSCode
https://github.com/microsoft/vscode-languageserver-node/blob/7792b0b21c994cc9bebc3117eeb652a22e2d9e1f/protocol/src/common/protocol.ts#L1504C18-L1504C59

**Comment by dbaeumer** [comment]
The right documentation point is here: https://github.com/microsoft/vscode-languageserver-node/blob/cb7d5e68206741f86ebe0695855b29c55d59b278/protocol/src/common/protocol.configuration.ts#L13

So when using the pull model all you can register for is a configuration change even with no sections since the client has no knowledge about what the servers pulls in which scope.

So the registration in the pull model should look like this:

```
connection.client.register(DidChangeConfigurationNotification.type, undefined)
```

**Comment by lukaszsamson** [comment]
OK, so the language server should expect a 'workspace/didChangeConfiguration' notification with
```
{
    "settings": null
}
```
and call `workspace/configuration` to get the actual values.
What about `DidChangeConfigurationRegistrationOptions`? Shouldn't it be mentioned in the spec? It's an exported type

**Comment by dbaeumer** [comment]
Since the old push model is deprecated I would like not add it since servers should use the new pull model,
