### ISSUE TITLE
How should cancelled requests be handled?

### ISSUE THREAD

**Issue by ljw1004** [Microsoft/language-server-protocol#185]
The spec explains: "A request that got canceled still needs to return from the server and send a response back. It can not be left open / hanging." But what should it return?

__OPTION 1:__ The way I'd like to deal with this is by having the server free to send back a ResponseError with an "OperationCancelled" error code. But I'm too scared to do this in case VSCode responds to unknown error codes by popping up a UI dialog to the user.

*REQUEST: LSP protocol should define a new `ErrorCode.OperationCancelled` number that clients of LSP should respect. For instance if the client sends a Completion request and gets back an OperationCancelled response then it'll know to simply not show completion.*

__OPTION 2:__ Another way is if the server sends back an "empty" or "partial" result. This requires the server to do work to figure out, for each request, what is the smallest cheapest valid response it can give, one that won't confuse the client. And then it has to trust that the client won't cache this response (which is a valid fear for operations like autocomplete, definition and hover).

__ADDITIONAL NEED:__ The LSP spec currently puts the entire burden upon the client to cancel unneeded requests. It would be better to let the LSP shoulder this burden if it wants. For instance, imagine the client sends a "hover" request over one location, and the user moves the mouse, and the client needs to send another "hover" request. We could do it by requiring the client to cancel the first request, or we could do it by having the server realize that the first request has been superseded and so cancel it on its own. The server already owns its queue of incoming requests, so the server is the cleanest place to code this logic.

__Thoughts on caching__. Imagine a client which caches the results of completion or hover. How should it know whether a response should be cached or not? If the client is the only one who initiates cancellation requests, then the client must maintain a log of all outstanding cancellations, so that when it gets back a response it can avoid caching responses to cancelled requests. But if the server is the one who initiates cancellation, then the client needs some other way to know not to cache the response. I think that `ErrorCode.OperationCancelled` would be a neat way for the client to know this.

**Comment by dbaeumer** [comment]
@ljw1004 May I ask you what you are working on. You file quite some good remarks about the protocol.

I like the idea of adding a error code for OperationCanceled. That makes perfect sense. I will update the protocol and our library implementation. One remark: since this is an addition I can't enforce it. So it will be an advice :-).

The other ideas depend IMO very much on the technology used in the client and the server. So I am reluctant to spec this. These should be implementation guide lines. Here is what we do in our libraries:

- VS Code itself has the concept of cancellation. So in our example we send a hover request to an extension running in VS Code. If VS Code doesn't need the result anymore since the mouse got move VS Code cancels the hover request in the extension (not in the server). See the CancellationToken inside VS Code.
- The vscode-languageclient library listens on cancellation tokens for open request. If cancellation is requested the library send a cancellation notification to the server.
- If the server uses our vscode-languageserver library then every request executed by the server has a CancellationToken as well.
- If the server receives a cancellation notification it signals this with the cancellation token.

It is the up to the specific request to decide what the best way is to response to this. 

IMO we should not add too much smartness to the protocol or force special implementation for the client and server libraries. A client library can not by itself decide to cancel a request due to the fact that a new request will be send with the same arguments. May be the client has some smart logic to reuse parts of the first result with the second and the request was only send because a third file changed. The library must depend on the client to signal cancellation.

**Comment by dbaeumer** [comment]
Closing. @ljw1004 please ping if something is still unclear.

**Comment by ljw1004** [comment]
Thanks @dbaeumer!

I'm working on an LSP provider for the Hack language, and LSP client for the Nuclide IDE. I'm writing the Hack server in OCaml (since that's what Hack is written on) so I'm having to implement it from scratch. And Nuclide can't take advantage of the LanguageClient either. Hence, I'm looking over every part of LSP in minute detail! And since we have an already-existing experience with Nuclide+Hack with an existing user interface, I have to make the switch to LSP won't regress anything.
