### ISSUE TITLE
What's the difference about deprecated in Diagnostic and Semantic Token?

### ISSUE THREAD

**Issue by imbant** [microsoft/language-server-protocol#1865]
Hi there. There is a `SemanticTokenModifiers.deprecated` and a `DiagnosticTag.Deprecated`.

In TypeScript, a variable tagged deprecated by jsDoc(`// @deprecated`) will be added a strikethrough. 
I tried semantic one but in my VS Code, most color themes don't support adding strikethrough to a token.
So I guess ts language server may use diagnostic one to implement that.

Is that the best practice to add strikethrough? If few themes add strikethrough to the deprecated semantic tokens, what is the usage of this semantic token modifier?

**Comment by dbaeumer** [comment]
As always LSP doesn't define detailed rendering so it is up to the client to decide how to render `deprecated` for both semantic tokens and tags.

We had `DiagnosticTag`s long before semantic tokens. This is why both exists.  I would actually use tags since more clients will support them that semantic tokens.

**Comment by imbant** [comment]
@dbaeumer I got it. Thanks for your time
