### ISSUE TITLE
Clarify whether a server must respond to a shutdown request

### ISSUE THREAD

**Issue by KalitaAlexey** [Microsoft/language-server-protocol#188]
Currently it is unclear whether a server must respond to a shutdown request in order to receive exit request.
It is also unclear whether the result must be undefined/null or any other value.

**Comment by dbaeumer** [comment]
Since the shutdown is a request it MUST responsed with a Response object. This is how JSON RPC is defined. The result is void. Since JSON rpc requires the result field set to something in the JSON literal we set the result to null if a request doesn't have an explicit result. Undefined can not be used since undefined is not a valid value in JSON (e.g. `{ result: undefined }`) is not valid JSON.

**Comment by dbaeumer** [comment]
A good read for this is http://www.jsonrpc.org/specification.

I add

> If a request doesn't provide a result value the receiver of a request still needs to return a response message to conform to the JSON RPC specification. The result property of the ResponseMessage should be set to `null` in this case to signal a successful request. 

to the protocol.
