### ISSUE TITLE
Explain multiple language server selection

### ISSUE THREAD

**Issue by gorkem** [Microsoft/language-server-protocol#200]
The protocol needs to explain how the language servers are selected when multiple language servers are registered to work on the same artifact. This can provide guidance to especially adopting clients and improve consistency.

**Comment by mickaelistria** [comment]
I don't think it's something the protocol can easily specify. Multiple opposite strategies are possible, and there isn't one that seems much better than the other. For example
1. a LS providing basic XML grammar support + a LS providing specific additions for some tags => you'd like your editor to show the results of both servers
2. a LS providing basic XML grammar support + a LS built on top of it providing XML grammar and additions for some tag => you'd like your editor to show only the later one.
The protocol might provide way to help integrators and editors to take the best choice, but I don't think it's a good thing to enforce an architecture for such.

In LSP4E, we do merge the results of all LS whenever possible, and try to deduplicate results (in completion for instance). However, it's quite weak.
Note that for diagnostics/error reporting, it's not much an issue to get 2 markers for the same error.

**Comment by dbaeumer** [comment]
Agree with @mickaelistria. This is nothing the protocol can specify since it is a client/tool decision and should be consistent with the tool. For example VS Code merges the results since it also merges the results from 'normal' extensions (no server implementations) for things like code complete. For formatting it picks one based on user settings and scores. 

Another client may only honor a single extension for a language feature. In this case if language features are implemented using a server then it should honor the same strategy. Otherwise the user experience in the tool is hard to understand.

I will close since I believe leaving this up to the client to make client behavior consistent is the right thing to do.
