### ISSUE TITLE
Is debug protocol in roadmap?

### ISSUE THREAD

**Issue by lennylxx** [Microsoft/language-server-protocol#210]
In this page, it mentions that debug extensions of VS Code are using **_VS Code debug protocol_** to interact with VS debugger UI.
https://code.visualstudio.com/docs/extensions/example-debuggers
So I'm wondering whether standardization of debug protocol is in roadmap?

**Comment by mickaelistria** [comment]
This is more a question for https://github.com/Microsoft/vscode-debugadapter-node/tree/master/protocol

**Comment by lennylxx** [comment]
@mickaelistria Yes, it's the Microsoft implementation only for VS Code editor. I mean once it's standardized, other editors/IDEs like Eclipse can also using that protocol.

**Comment by mickaelistria** [comment]
The repository I linked contains the VSCode implementation, but also a definition of a protocol which is defined in a similar way as the language-server-protocol: https://github.com/Microsoft/vscode-debugadapter-node/blob/master/debugProtocol.json . Any client is free to support the message types defined in the protocol in order to interact with the debug adapters that conform to the protocol.
Anyway, I believe the debug part is out of the scope of the language-server-protocol. It's better keeping them separated like they are now; and I believe you should open an issue against https://github.com/Microsoft/vscode-debugadapter-node/ to request extraction of the plain protocol part in its own repo, separated from the VSCode implementation.

**Comment by egamma** [comment]
This is on our radar and we are thinking along the lines of @mickaelistria in the comment above. I'm therefore closing this issue since it doesn't belong to this repository.

**Comment by weinand** [comment]
The debug adapter protocol specification (and the generated TypeScript definitions) are independent from the VS Code implementation and live in their [own repository](https://github.com/Microsoft/vscode-debugadapter-node) (but that repository still uses "vscode" in its name). 

Moving the debug adapter protocol specification/schema to a separate repository is planned. See https://github.com/Microsoft/vscode/issues/19636.
