### ISSUE TITLE
Allow to register for file events dynamically

### ISSUE THREAD

**Issue by ljw1004** [Microsoft/language-server-protocol#212]
_Spec_ says "The watched files notification is sent from the client to the server when the client detects changes to files watched by the language client."_

It doesn't say which files are watched by the language client. Which ones can the server expect? Is it guaranteed to be at least as big as the set of files that are currently open in the client?

_@akosyakov wrote "I assume DidChangeWatchedFiles notification is sent when physical files belonging to the workspace are created, changed or deleted, regardless to open documents." and @dbaeumer agreed._

But that's fishy. The notion of "files belonging to the workspace" doesn't exist in LSP, and when the client sends an Initialize request to open a project, then only the SERVER (not the client) knows the set of files in this project. There's no way for the client to enumerate them.

So: which "watched files" is a client _required_ to send DidChangeWatchedFiles notifications for?

I see that the vscode-nodeserver example has a concept of watched files. But that's a vscode-specific thing, not part of LSP...

**Comment by dbaeumer** [comment]
This is currently up to the client to decide. This request got added as a information vehicle not has a file watcher per see. If the vscode client library is used the extension needs to instruct the client library which files to watch and to sent notification to the server too.

The way how that should work with dynamic registration is that we allow the server to register for file events instead of making this a client decision. I simply forgot to do so when introducing dynamic registration. Will change the title so that we can work on this.

**Comment by dbaeumer** [comment]
This got implemented a while ago and is part of the protocol and the node implementation.
