### ISSUE TITLE
Publish Diagnostics for multiple sources

### ISSUE THREAD

**Issue by alanz** [Microsoft/language-server-protocol#228]
Where there are multiple tools on the server side each generating diagnostics asynchronously, it is not clear what the expected behaviour is at the client when receiving a `textDocument/publishDiagnostics` notification: 

- The server sends the union of the diagnostics from each tool fully each a new report is received, so the client replaces the diagnostics for a given file each time a new notification is received.
- The client partitions the diagnostics according to source, and only overwrites diagnostics with matching sources.

**Comment by dbaeumer** [comment]
The behavior is replacing since there is not way the client could group the diagnostics. We would need to add something like an owner field to Diagnostics to allow n groups per server. If you feel strong about having this support, please open a feature request. However I think a server can handle this my sending the diagnostics when the n providers have completed.

**Comment by alanz** [comment]
That behaviour is fine, but the spec should say so, so that all clients do it the same way, and it is clear.

**Comment by dbaeumer** [comment]
That is true.
