### ISSUE TITLE
Clarification of how to support multiple editors of the same buffer

### ISSUE THREAD

**Issue by dumblob** [Microsoft/language-server-protocol#23]
From the current specification it's not clear to me how the server should handle simultaneous access of multiple clients editing the same buffer.

Could you please clarify how is this situation handled?

**Comment by bruno-medeiros** [comment]
Why would a user use multiple IDEs to edit the same file? Seems like a really odd case.

**Comment by dumblob** [comment]
Well, nowadays we use more than one computer (think of a desktop, notebook, smartphone, tablet, phablet, ...) and on each of these there are different editors/IDEs.

Also guys performing pair programming or other methods involving real-time close collaboration between individuals having different preferences of editors/IDEs (yes, good old religious wars) would highly welcome this.

**Comment by gorkem** [comment]
I think multitenancy is the real question here. It is the editor's responsibility to resolve the issues around shared buffers or buffer synchronization etc. However protocol does not provide much guidance on a server that support multitenancy and assumes one server instance per editor instance.

**Comment by dbaeumer** [comment]
I think there is a difference between multitenancy and two editors editing the same buffer. The protocol should be able to handle multitenancy as long as the client setups a distinct channel to the server per user/workspace. How this should be done is not part of the protocol itself but could IMO be an extension to it. Opening two editors on the same buffer needs major modifications to the text document part of the protocol.

**Comment by dbaeumer** [comment]
I will for July clarify what the current assumptions are.

**Comment by dumblob** [comment]
>How this should be done is not part of the protocol itself but could IMO be an extension to it.

Ok, is there any tracker for extensions or extension proposals?

>Opening two editors on the same buffer needs major modifications to the text document part of the protocol.

This is though an inevitable feature which e.g. Vim/Neovim, Emacs and most probably other editors as well handle gracefully already for more than 20 years. I use it every day and basically all other guys I know do the same.

**Comment by bruno-medeiros** [comment]
When you guys say "Opening two editors on the same buffer", what exactly do you mean here ? The terminology is not clear to me.

Are we talking about about two editor-applications opening a document for the same file location (say Emacs and VSCode both editing the same file)?
Or are we talking about two editor-widgets within the same editor-application? (say, two editor tabs within Eclipse) ?

In Eclipse for example, it is indeed possible to open multiple editor-widgets for the same file, each editor-widget having its own buffer/document with different contents. However I personally think this is a bad design (among other problems, it interacts badly with auto-save, because the two documents race each other when being saved to disk). On the Eclipse side I'd like to see this behavior removed by default. (I'd champion an effort to change this, but in Eclipse it's very hard to change existing app behavior, unfortunately)

On a very similar note, I don't see the point of using multiple editor-applications on the same file. This is a strange scenario that would needlessly complicate LSP. @dumblob You mentioned pair-programming with people swapping roles (from driver to observer) but using different editors. Well, if that happens, just invoke the Save-All-Files of your editor-application when someone else switches into another editor-application. Problem solved. Basically, the only gain of implementing multiple editors for the same location in that scenario is saving that keystroke, whenever someone switches chairs.

**Comment by mickaelistria** [comment]
This is somehow related to my question on #38. From a given client, as long as there is no way to know the "state" on the server side (such what's the buffer it's using for a given resource), it seems impossible to deal with synchronization between 2 different clients using the language server protocol.

> In Eclipse for example, it is indeed possible to open multiple editor-widgets for the same file, each editor-widget having its own buffer/document with different contents. However I personally think this is a bad design (among other problems, it interacts badly with auto-save, because the two documents race each other when being saved to disk). On the Eclipse side I'd like to see this behavior removed by default.

It's possible, but IIRC the behavior of many Eclipse editors is to reuse an existing document if it's already open. So "internal" synchronization of 2 files inside the same Eclipse IDE is a topic that already has a solution and that shouldn't be considered for LSP.

> This is though an inevitable feature which e.g. Vim/Neovim, Emacs and most probably other editors as well handle gracefully already for more than 20 years. I use it every day and basically all other guys I know do the same.

Don't Vim or Emacs use the same internal representation of the document when editing in multiple editors? If so, then it seems like the current state of LSP allows to bind the underlying share documents to the language server and this would work as expected.


Overall, it sounds like a good thing to allow simultaneous edition in different editors and multi-tenancy, but pragmatically, there have been tools allowing this for years and years and none manage to get actually much used (useful?) in real life. So I don't think it's a necessary direction to follow.

**Comment by dbaeumer** [comment]
I clarified this in the documentation. I will keep the issue around in case we want to work on concurrent editing.

**Comment by dbaeumer** [comment]
To keep the number of issues in our inbox at a manageable level, we’re closing issues that have been on the backlog for a long time but haven’t gained traction: we look at the number of votes the issue has received and the number of duplicate issues filed. Thank you for your time and understanding.

If you disagree and feel that this issue is crucial: we’re happy to listen and to reconsider.
