### ISSUE TITLE
Make file watching an optional client capability

### ISSUE THREAD

**Issue by mickaelistria** [microsoft/language-server-protocol#237]
I have the impression that the didChangeWatchedFile notification is too much. Why do we need it when we already have didChange/didSave? It seems simple to send a didChange and/or a didSave for a file (even if it wasn't open first) when we see a change. What makes the watches files so special?

Overall, I think this operation is too much, and the real issue when trying to consume watched files is more to be informed from the server about which files to watch.

Cf https://bugs.eclipse.org/bugs/show_bug.cgi?id=516216

**Comment by akosyakov** [comment]
Do you mean that it should be a responsibility of a server to watch a root directory, not a tool? And `didChangeWatchedFile` is redundant because of it?

**Comment by akosyakov** [comment]
@dbaeumer Why a language client should be a source of file changes? It makes sense to me in the case with documents, but thinking about files, language servers have direct access to a file system  compare, for example, to a client running in the browser. In such cases a client should be first notified about changes and then dispatch them between servers, which could introduce additional traffic and latency.

**Comment by mickaelistria** [comment]
```
DidChangeWatchedFiles Notification

The watched files notification is sent from the client to the server when the client detects changes to files watched by the language client.
```
and
```
DidChangeTextDocument Notification

The document change notification is sent from the client to the server to signal changes to a text document.
```
It seems like those 2 operations do the same thing. The only difference is `files watched by the language client`. If so, it could be better to merge both notifications, better define `files watched by the language client` and probably create a dedicated option in capabilities to be informed about what those files are.

**Comment by vladdu** [comment]
didChangeWatchedFiles only notifies that something has changed, without sending the change. So it's a lightweight system, where using didChange could mean sending potentially hundred of megabytes of text (if a Java project changes JRE, for example).

If the server can keep track of the changes itself, I suppose it's not mandatory to send these messages at all, but we don't know what the server supports, because there is no server capability that lets the client know about that and there are a lot of servers out there.

**Comment by cdietrich** [comment]
suppose you open a folder in the client.
the folder has 2 files
the first file is opened in the client and this gets `didChange` messages.
now the second file is changed on hd e.g. via git update etc.
now the client informs the server about this change via `didChangeWatchedFile`
and the server can react on this an reindex/validate etc this file

**Comment by mickaelistria** [comment]
@cdietrich: ok, but wouldn't a didChange notification allow to do the same thing?

**Comment by mickaelistria** [comment]
@vladdu thanks, that's an interesting point. Maybe it would make sense to allow `didChnge` to not pass text content and retrieve it from the LS workspace?

**Comment by cdietrich** [comment]
well why then a `initialize` request if the client can open all files and close the unwanted ones?

**Comment by akosyakov** [comment]
@mickaelistria `didChange` is about a client state which is not necessary persisted, if the client don't pass it then the server cannot know about it and would work with outdated state from the disk. We should not mix it with `didChangeWatchedFiles` which notify about changes on the disk.

I wonder why file changes should go through a client and potentially, when a client does not live  next to the disk, creates network latency. If we remove this event and force servers decide what, when and how to watch, it simplifies a client side code and improves performance.

At least it could be worth while to add something like `ClientCapabilities.workspace.watchFiles` to test whether a client supports file system watching.

**Comment by mickaelistria** [comment]
> We should not mix it with didChangeWatchedFiles which notify about changes on the disk.

So it's a bit like `didSave` then?

> I wonder why file changes should go through a client and potentially, when a client does not live next to the disk, creates network latency. If we remove this event and force servers decide what, when and how to watch, it simplifies a client side code and improves performance.

+1

**Comment by vladdu** [comment]
If I understand correctly, the current assumption is that client and the server are at the same distance from the disk, and then it doesn't matter which one watches it. But in theory, the disk could be close to the client, or to the server, or to neither. The server and client need not even share the filesystem, if they can handle http:// URIs. Of course, this is speculative at the moment.

**Comment by dbaeumer** [comment]
Great discussion. Some historical background why we decided to add this:

- to our experience getting file watching on disk right is challenging, especially if it needs to be supported across multiple OSes.
- file watching is not for free especially if the implementation uses some sort of polling and keeps a file tree in memory to compare timestamps (as for example some node modules do) 
- if a client starts n servers (which it usually does) n servers need to get this right plus we have n servers doing the watching

So we thought that it would make sense to forward these file change events to the server since most tools already what the file system.

What is the difference to didChange: didChange events are only send for document for which a didOpen got send. didOpen, didChange, didClose is the live cycle of a document buffer and the buffer must not necessarily exist on disk.

I like the idea of adding a client capability to signal if a client can provide these events at all. And one thing that I missed to spec and implement is that a server can dynamically register for file events or ask for file events on the initialize result. We should add both to the spec and implementation.

**Comment by akosyakov** [comment]
@vladdu It is not in theory already, there are applications, like [RBrain](https://r-brain.io/en/) or [sourcegraph](https://sourcegraph.com/) which run clients in browsers and use git as a disk for example.

**Comment by akosyakov** [comment]
@dbaeumer your points are valid, but it could be solved out of scope of the LSP:
- like providing libraries for language servers;
- or deploying a file server next to the disk that notifies both clients and servers directly

In that case watching logic will move from tools' extensions to servers. Right now it is duplicated among extensions for different tools.

**Comment by guw** [comment]
@dbaeumer Thanks for the background. 

I think it's challenging to keep it that way, though. More heavy-weight servers that come with their own index, need some form of index reconciliation on startup to catch up on changes that happened while the server was off-line. Should it become part of every tool/extension to implement a per-server delta/change tracking?

Also, when this becomes an optional client capability, those heavy servers may be required to implement it themselves anyway in order to be interoperable with many tools. From a server implementor's point of view, I think it's a maintenance-/test-nightmare to rely on functionality implemented independently by each tool. There won't be two single tools behaving exactly the same.

I like the idea of providing/recommending libraries to server implementors where available.

**Comment by dbaeumer** [comment]
I am not saying that a server can't add its own file watching. With the 3.0 version of the protocol I made the option dynamic anyways so a server can simply not register for file events and run its own library. We can if necessary add a property to the initialize request as well. If a server doesn't register for file events and the client library is not instructed to send any then a server currently doesn't receive any file change events. 

But removing this options is not a good idea either since it puts quite some implementation pleasure on simple servers as well that are interested in watching some files. 

I opt to close since it is possible to implement a server that does its own file watching.

**Comment by dbaeumer** [comment]
Moving to 4.0 to consider client capability setting and server initialize setting.

**Comment by tsmaeder** [comment]
@dbaeumer the explanations in this issue are great. It would be awesome to have them in the actual doc ;-)

**Comment by dbaeumer** [comment]
I updated the spec with some of the comments from here. Whether this should become an optional feature is open for discussion however will break existing servers.

**Comment by ShaneDelmore** [comment]
I see it alluded to, but not explicitly mentioned.  The server and client may not live on the same machine.  For companies with large code bases there may be benefit in running a remote server so I would prefer not to assume the server is always local to the client.

**Comment by dbaeumer** [comment]
@ShaneDelmore this is another topic and discussed in another issue. The current protocol is not tailored for 
- remote servers
- multi tenant servers
