### ISSUE TITLE
Examples of LSP with WSL.

### ISSUE THREAD

**Issue by jordwalke** [Microsoft/language-server-protocol#259]
Are there any examples of using LSP from a Windows editor such as VSCode, but using a server running inside of WSL?

**Comment by dbaeumer** [comment]
No, such an example doesn't exist right now to my knowledge.

**Comment by jordwalke** [comment]
It seems like a very natural thing to want. I hope someone can point us to a working example. Does LSP work over a completely serializable bridge? If so, shouldn't it just be a matter of proxying the communication?

**Comment by felixfbecker** [comment]
I don't see any reason why it shouldn't work. Are you facing any specific difficulties? You can just spawn `bash -c <language server>`

**Comment by dbaeumer** [comment]
To keep the number of issues in our inbox at a manageable level, we’re closing issues that have been on the backlog for a long time but haven’t gained traction: we look at the number of votes the issue has received and the number of duplicate issues filed. Thank you for your time and understanding.

If you disagree and feel that this issue is crucial: we’re happy to listen and to reconsider.
