### ISSUE TITLE
[suggestion] enrich the client API

### ISSUE THREAD

**Issue by akosyakov** [Microsoft/language-server-protocol#292]
The protocol supports execution of commands by the server. Currently, the server can only apply document changes and show notifications to the user. Will not it make sense to add more features, e.g. trigger `hover`, open some URI, reveal another selection, add something to the clipboard and so on? At least for features which already covered by the protocol, e.g. if the tool can call `textDocument/hover`, obviously it should have the hover support.

Right now implementors can provide custom messages and implement them for each tool. Would be interesting to know which features are most relevant? E.g.: I am aware that Java LS shims to call find references (lsp types -> vscode types). It would be better if such shimming done once by the tool, not by each server.

**Comment by mickaelistria** [comment]
I imagine it would be easier to discuss each proposal individually and to
enrich the spec incrementally. Can you please create dedicated issues with
user-stories to support the addition?

**Comment by dbaeumer** [comment]
@akosyakov I opened up the vscode specific npm modules to easier add protocol extensions and wrote a guide on how to contribute a protocol extension to the LSP [here](https://github.com/Microsoft/language-server-protocol/blob/master/contributing.md). I will close the issue in favour of trying the new contribution approach so that we can polish and tweak it.
