### ISSUE TITLE
Support for multi-tenancy

### ISSUE THREAD

**Issue by object88** [Microsoft/language-server-protocol#294]
I think that this has been hashed out a little here, but I'd like to put in my request.  I am thinking about the scenario where I have multiple editors open locally, talking to a single local language server.

In particular, on my laptop, I have three instances of VSCode running, each with different file structures, but a common standard library (i.e., they are all Go projects with a common `GOROOT`).  It would save on resources if I had a single language server running on one socket, that was able to digest the standard library resources once and keep it shared among clients.

Currently, if I have multiple VSCode instances running, it appears that they would each have to have their own language server instance, recurring common costs.

**Comment by kdvolder** [comment]
I don't think that's true, I think its really totally up to you how you 'launch' the server. For each server you tend to write a little bit of 'wrapper code' that is responsible for launching the server and establishing a connection to it from the client side. The common thing to do is to launch a new process and us the launched process's sysout/sysin streams as the 'pipe' to talk between client / server.

But it is perfectly feasible to instead use a single shared server process, establish a socket connection to the server process and then connect the client on the in/out streams provided by the socket connections. For this to work, your server has to implement some kind of session scope so that different socket connections each establish their own session and keep the state for different connections separated (e.g. as in your case each connection would track the state of different set of open documents).

But, the way I see it, these are implementation choices and they don't have anything to do with the spec. The spec doesn't really say how you should manage the server processes, it only specifies the communication protocol itself.

**Comment by object88** [comment]
Hm.  I'll be honest, I'm learning a lot about network communications (being something of a traditional HTTP kind of guy so far) while digging into this, so I will look into maintaining a session scope across a socket connection.  Thank you for this feedback, I greatly appreciate it!
