### ISSUE TITLE
Clarification: Using `goto definition` on non-identity token

### ISSUE THREAD

**Issue by object88** [Microsoft/language-server-protocol#296]
Given some Go code:
``` go
type Foo struct {}
var f Foof
```
What should be the behavior if I request the definition of `struct` or `Foof`?  In the first case, it's a  keyword, so I would not expect any source to define it.  In the second case, it's just not defined anywhere.

The spec for [`Goto definition`](https://github.com/Microsoft/language-server-protocol/blob/master/protocol.md#goto-definition-request) indicates that the response should include a Location or array of Location, and an error (code and message) in the case of an exception.

In several places in the spec, it seems as though an error is when the server malfunctions.  In this case, there is simply not a matching location in the code.  In these instances, should the server respond with an empty location?
``` json
{
  "uri": "",
}
```
Is there a well-describe shape of a "non-location" response?

**Comment by object88** [comment]
VSCode seems to be happy if you provide an empty response (i.e., no `Location` at all), but it would be good to understand if this is the expected behavior across all clients.

**Comment by kdvolder** [comment]
To me this is just vscode being 'nice'. It saw that the server returned 'nonsense' and chose not to throw a fit but simply ignore that 'garbage'. I think that's a sensible thing for any client to do, but its really up to the client implementation to decide how to deal with servers that return 'garbage'.

Reading the spec, there seem to be three different ways to respond:

1. return an error message
2. return one or more locations
3. return an empty array of locations.

Case 3. seems to be the intuitive / appropriate way to convey that the thing being pointed at doesn't/shouldn't respond to 'goto definition' and this isn't really because of some 'problem', buts normal behavior. So, it seems, this how you should convey there's no corresponding definition, rather than by returning some bogus location with an empty uri string.

**Comment by object88** [comment]
I agree that responding with a partially complete `Location` object (`{ uri: "" }`) is bad.  To be clear, VSCode complains about this.  VSCode seems to not mind if the JSONRPC2 "result" on the response is missing or empty (I haven't dig far enough in to know which).  

So, this starts to get kind of interesting.  At first I was confused by the possibility of multiple values of `Location` for a single definition, but it seems to me that might be useful for C# with `class` and `partial class`.  Most commonly, there would only be one location, so it seems a little strange that to indicate "no location", and empty array would be returned.

No of responses | response
--------------- | ---------
0 |  `[]`
1 |  `{ uri: "foo.go", range: { start: 45, end: 48 } }`
2+ | `[ { uri: "foo.go", range: { start: 45, end: 48 } }, { uri: "bar.go", range: { start: 35, end: 38 } } ]`

If an empty array is used to indicate that there's no location, than the "outlier" is the case where there's only one location (even if it is the most common).  For the simplicity of the spec, I wonder if it's better to always send the response as an array.

Alternately, does it make more sense to allow a `Location` to be "empty" (`{}`) if there is no match.  Then the "outlier" is the multi-location, which should be uncommon.

**Comment by kdvolder** [comment]
I'm just guessing here. Might be wrong, the reason why you can send either a single Location or an array may have something to do with backward compat. Perhaps, at one time, you could only send a single location, then some case appeared where it was useful to send more than one and the 'array' option as added to support that. In order to not break older servers, it is still allowed to just send a single location. Also, that is convenient if your server doesn't really have cases where it wants to send multiples.

Whatever the case may be, to me, it looks like there's nothing wrong with how its spec-ed. You just send empty array to say 'nothing to show here'. To send a single location, you can choose to send it in an array, or not. That's slightly more complex than it needs to be, but that doesn't harm anyone.

So I think this ticket should probably be closed.

To be clear, I'm not really part of the team maintaining the spec, I'm just an interested outsider like yourself. So this is only my opinion, nothing more.

**Comment by object88** [comment]
That's a fair point, that it probably is perfectly legal to send a single value inside an array.

I think that the protocol.md is still a little lacking with regard to no-location (even if no changes are necessary to existing behavior is necessary), so I'd like to get some input from the maintainers.  Based on that, I'd want to submit a PR to clarify.

(Also, I appreciate your opinions, thank you for taking the time!)

**Comment by dbaeumer** [comment]
@kdvolder is correct. We started with a single location and then with support for other programming languages (C#, Java) we noticed that there doesn't have to be a single unique place for a definition. 

The there is no result case should be indicated by allowing `null` as the return value. I will update the spec.

**Comment by object88** [comment]
Thank you, @dbaeumer and @kdvolder!
