### ISSUE TITLE
Remove process ID from the initialize request

### ISSUE THREAD

**Issue by jared2501** [Microsoft/language-server-protocol#30]
Why is this needed? Surely any server could query the operating system for this information?

**Comment by svenefftinge** [comment]
It is the process Id of the client (tool). It is used to let the server process die, in case the client died.

**Comment by dbaeumer** [comment]
The reason is that the server could be started 'detached' from the client. So the comment is not accurate in that regard. That is why we decided to include the process id of the process that started the server. In addition Linux and Mac have the concept of orphaned processes. To make server cleanup easier in cases the tool crashes having this information is beneficial.

What I think we should do is the following: leave the processId but make it optional in case a server is running as a demon.

**Comment by dbaeumer** [comment]
The spec allows `null` for the processId. Closing the issue.
