### ISSUE TITLE
Clarification: for `didOpen`, can server read from disk?

### ISSUE THREAD

**Issue by object88** [Microsoft/language-server-protocol#302]
This is a pretty minor point.

The [`didOpen`](https://github.com/Microsoft/language-server-protocol/blob/master/protocol.md#textDocument_didOpen) notification description says "... and the server must not try to read the document's truth using the document's uri."  And the params pass the content of the file to the server (at least with the set of params I have configured?).

It's clear to me why the server wouldn't want to do this after the file is opened; it's getting edited by the client app.

I'd like to better understand if there's some reason why the server _shouldn't_ read the text document from the disk _at the time of notification_.  Is there any reason that we can't?  I.e., if I can convince the client to not pass the entire text document contents on that notification, can I get the server to read directly from disk instead?

(This might be a moot point... if the client has already read from disk, it might be cheaper to send it over the connection to the server, than have the server read it again.)

Thanks for any thoughts on this.

**Comment by dbaeumer** [comment]
The reason is that the whole protocol is async and that therefore there is currently no guarantee that both the client and the server read the same content (there can be a third app writing the file). 

If we want to not send the content (which makes sense for very large files) then we need to enhance the protocol in the following way:

- client includes a hash of the file
- server checks the hash, if not equal the server needs to request the content from the client.

I will close the issue. @object88 please open a separate issue if you think the protocol must support that the server can read a file and that there is a handshake protocol to agree on the same starting version.

**Comment by object88** [comment]
Thank you for the explanation!  For my purposes, files are small, and I am not concerned with sending them across the wire, so I don't need another issue.
