### ISSUE TITLE
Cursor position (snippet) support for textDocument/codeAction

### ISSUE THREAD

**Issue by yaohaizh** [Microsoft/language-server-protocol#308]
For textDocument/completion, it support cursor position(snippet) from textDocument/completion according to this https://github.com/Microsoft/language-server-protocol/issues/75

Does the codeAction support snippet or not? As I tried, it seems doesn't work.

**Comment by dbaeumer** [comment]
Code actions currently don't support snippets. In general code actions don't even provide means to provide edits. The flow is usually as this:

- server returns code actions (could be many)
- user selects code action
- server is informed about the code action selected
- the server generates some edits and applies them to the buffers in the editor.

Since edits are more powerful than snippets the server can manipulate the document in any way.
