### ISSUE TITLE
filtering "documentSymbol" operation

### ISSUE THREAD

**Issue by vladdu** [Microsoft/language-server-protocol#312]
It is sometimes useful to know the value of the symbol at a given location, for example to show the original name of a symbol being renamed. The full documentSymbol can be used, but it can be quite heavy to return the whole list. So I would like to suggest to add an optional location or range parameter to DocumentSymbolParameters, asking for only the symbols within that range. The default (no range) would of course give the exiting behaviour.

**Comment by dbaeumer** [comment]
No sure I understand this. Wouldn't executing a hover request at the position give you exactly this information.

If not I am more for having a resolve symbol request than adding a range to the document symbol.

**Comment by vladdu** [comment]
Hover returns a range that is not necessarily linked to a single symbol. I don't have an example handy, but can ask the guy who told me about it :-)

I thought that this would be a smaller change, but a separate request would work just as well for me.

**Comment by dbaeumer** [comment]
There were a lot of discussion lately about ranges. In general the LSP is not a AST API. It is tailored to integrate a language into an editor not to reason over a programming language. So for document symbols the range must not necessarily be the exact symbol range either. It is the range the editor should show to highlight the symbol.

**Comment by vladdu** [comment]
I think I understand your point of view, but I am not convinced. "Integrating a language into an editor" is a kind of "reasoning over the language". We restrict that to what is useful for an editor to handle, yes. If the editor will need to create and maintain an AST for some operations, then the reason for using a LS isn't there anymore.

Anyway, textDocument/documentSymbol already returns this information as part of a larger body of data. Filtering that data to a range can be useful even for the use case where the document is huge and the editor only wants information about the symbols that are visible (for better responsiveness).

**Comment by kdvolder** [comment]
> It is the range the editor should show to highlight the symbol.

Even with such a 'high-level' description, it is still meaningful to distinguish high-lighting the whole definition or just the binding occurrence of the identifier. I.e. what I mean is, even if you take the point of view its just telling the editor what to highlight then the editor might want to highlight both of these ranges in different ways. E.g. in a 'peek definition' we might want to highlight the 'whole range' by showing it in the peek window, and the 'name range' by showing it in a different color/font. And in fact this exactly why I would like the server to be able to make that kind of distinction (and return both these kinds of ranges at the same time)... precisely so that vscode (or another client) would be able to display it better.

**Comment by dbaeumer** [comment]
I have no problem to have more ranges and to spec them precisely. However the spec has to be in terms what the editor should do with the result not in terms of AST or compiler model abstractions. 

I am not saying that such an API would be useful as well and yes may be it should go into a LSP at some time. However building these abstractions over different programming languages is IMO not easy to achieve. The easiness of the LSP is still that it talks editor abstractions and not compiler models.
