### ISSUE TITLE
Proposal: add a flag to textDocument/completions that resolves all CompletionItems

### ISSUE THREAD

**Issue by vincentwoo** [Microsoft/language-server-protocol#314]
Right now, if you want to write a client that automatically fetches all additional information for completion results, you have to do a fair amount of legwork. I think it would be useful for clients who are comfortable with slower response times to ask the server to automatically aggregate additional information into one request. This would simplify coding around partial failure in the case of one resolution request failing, for instance.

**Comment by kdvolder** [comment]
> This would simplify coding around partial failure in the case of one resolution request failing, for instance.

Simplify for the client, but what about server implementations? You are basically asking the servers to become more complex. I.m.o shifting complexity from the client to the server is bad trade-off. There are hopefully many servers and fewer clients.

And... to boot, I think client will nevertheless *still* have to handle all the complexity of the partial resolving case anyway because if you want the LSP protocol to maintain some kind of backwards compatibility, the client will have to assume there are clients who do not understand the 'please resolve everything' flag. So there will have to be some mechanic to enable this feature conditionally to support older server implementations.

**Comment by dbaeumer** [comment]
I agree with @kdvolder here. 

If implemented at all the server would need to flag this capability upfront to not break the protocol. Since I don't see this happening in the near future I will close the issue as inactive.
