### ISSUE TITLE
Clarification: can SymbolInformation point to a http:// resource instead of a file:// doc URI

### ISSUE THREAD

**Issue by martinlippert** [Microsoft/language-server-protocol#320]
I am experimenting with workspace symbols that contain a `http://...` URL instead of a URI to a text document. When the user selects such a symbol, a browser with that URL should open.

All that works already in VSCode (which is great). But the protocol defines the `SymbolInformation` to contain a `Location`, which contains a `DocumentUri`.

Question is: is it valid to use this for standard `http://...` URIs, too?
(and therefore on the client side to not rely on a file:// URL to be contained in a symbol)

**Comment by mickaelistria** [comment]
Hi Martin. If this is not supported in LSP4E, that would be a good
enhancement IMO. Although not specified by the protocol, it's a pragmatic
feature to support.

>

-- 
Mickael Istria
Eclipse IDE <https://www.eclipse.org/downloads/eclipse-packages/>
developer, at Red Hat Developers <https://developers.redhat.com/> community
Elected Committer Representative at the Eclipse Foundation
<https://www.eclipse.org/org/> board of directors

**Comment by martinlippert** [comment]
Sure thing, I will work on a patch for that for LSP4E: https://bugs.eclipse.org/bugs/show_bug.cgi?id=526272

**Comment by dbaeumer** [comment]
Yes it is valid. There is no restriction of the schema of the URI.

**Comment by kdvolder** [comment]
Maybe the real question here is not so much whether its possible to use `http://` (or whatever) uris, but if its possible to use a uri that doesn't correspond to a document but points to something like a web-page that should be opened by a web-browser instead of a document at a specific line in the editor.

For example, a Java editor could show symbol information for library functions and include a uri for some on-line Java doc to open in a browser. I.e a link like this:

https://docs.oracle.com/javase/8/docs/api/java/util/List.html#addAll-java.util.Collection-

I think vscode does something sensible with links like these, but as far as I know the protocol doesn't really explain how/if using uris in this way is supposed to be supported (and what the rules are on how a client should interpret the uris).

**Comment by dbaeumer** [comment]
I agree, but we shouldn't limit this. All I can think of is a client capability that specifies which schema type the client can handle. Opened #335
