### ISSUE TITLE
Executing commands

### ISSUE THREAD

**Issue by vladdu** [Microsoft/language-server-protocol#34]
How does the client requests that a command be executed? I can't see a request for that... 

Also, as specified, code actions (that use commands) seem to be related to markers - can they be used everywhere?

**Comment by dbaeumer** [comment]
The server currently doesn't execute commands. Commands mostly modify buffers which are best modified in the editor since open buffer must not be modified by the server (the ownership of an open buffer is strictly on the client).

However we are discussion certain ways to allows the server to compute buffer modifying command.s

If you want to implement a custom feature the protocol allows you to send custom requests to the server. However the server then might not work in other clients.

**Comment by dbaeumer** [comment]
Keeping for the modifying command discussion.

**Comment by vladdu** [comment]
Thank you. I'm not entirely sure I understand everything, though. This is how I understand it: 'CodeAction' is a request from client to server to return a list of possible actions that can resolve a diagnostic issue. The command handler name and arguments are sent back from the server. So the server has to know the client's handler names? I assumed that these values were sent back to the server to get executed, and the server would send the list of related text edits, much like 'Rename' does.

**Comment by david-driscoll** [comment]
Commands in general seem a little vague and seem to be very ambiguous.  It would be great if there was a well defined format for executing a known server command, so that the editor doesn't need need to understand the specific command.

**Comment by dbaeumer** [comment]
Agree. See also #62.

**Comment by dbaeumer** [comment]
I added this to the 3.0 proposal since it was a big whole in the current spec. It basically works as follows:

- the client sends a request executeCommand to the server without any assumption about what the server is doing. So it is a 'handler' invocation.
- in 3.0 the client can offer a applyEdit capability so that the server can apply a workspace edit manipulating n resources on the client side.

I am closing this issue. Please open a new issue if you want to give feedback on this new approach.
