### ISSUE TITLE
How do you handle unsaved changes?

### ISSUE THREAD

**Issue by Naatan** [Microsoft/language-server-protocol#341]
I'm currently working on a proof of concept client using, specifically on the textDocument/completion call as my test case. One issue I'm running into is the protocol does not make it evident how to handle unsaved changes. Ie. to show completions while someone is typing I can't just pass the URI of the file as the state of the file on disk is not the same as it is when the user is working with it.

What is the appropriate solution to this problem?

Thank you.

**Comment by rcjsuen** [comment]
@Naatan You should be listening for the `textDocument/didOpen` notification so that you are aware that the client has opened a file.

> The document open notification is sent from the client to the server to signal newly opened text documents. The document's truth is now managed by the client and the server must not try to read the document's truth using the document's uri.

After that, you should listen to `textDocument/didChange` as the client will inform you of (unsaved) content changes in its editor.

**Comment by Naatan** [comment]
As I said I'm building a client, not a server. I imagine this means the client needs to be sending these events. Is that really the common way of doing this? It seems a little convoluted. I mean no disrespect, I understand this opens the door for a number of things.

**Comment by rcjsuen** [comment]
@Naatan Oh, I'm so sorry. Most of the questions that happen here are usually about the server. :(

But yes, the client needs to be sending these events and this is how things are usually done. When the document changes the server needs to know that an opened file has changed so that it can update its internal model. For example, when a file changes the server needs to know so that it can parse the file again for generating compiler errors and warnings to send to the client via a `textDocument/publishDiagnostics`.

**Comment by Naatan** [comment]
I see. Thanks for the info!
