### ISSUE TITLE
Version number to use for a closed file in a TextDocumentEdit

### ISSUE THREAD

**Issue by rictic** [Microsoft/language-server-protocol#342]
Consider a rename, which may touch both open and closed files. It's desirable to use the versioned `TextDocumentEdit` interface for the open files, but what version should the server use to refer to closed files?

Sub-question: what if the file was opened earlier, and then closed, in which case we do have a last known version number?

**Comment by rictic** [comment]
A few options:
  * The client could be specced to ignore the version number when dealing with a closed file.
  * The server could be specced to send the most recent version of the file when it was open.
  * The client's versioning system could be specced so that at any given time, the next version number of a closed file (initially 0) refers to the file unmodified on disk, (to deal with cases like opening with a restored version of the file from unsaved changes).
  * The server could be specced to send a special value like `-1` to use when it expects an edit to apply to a closed file.

My preference would be for the final option, as it's very simple and expresses the intention from the server to the client.

**Comment by dbaeumer** [comment]
@rictic these are good questions and I agree that the server can't send a version number for closed documents since it owns these documents. 

Using `-1` as a version number for non open text documents might break existing clients since we never speced that a version number needs to start with `0`. So I opt to send `null` to make clear that the document is supposed to not be open. If it is (since the whole communication) is async we should reject the edit.

**Comment by rictic** [comment]
Null works for me.
