### ISSUE TITLE
Proposal: add ignored patterns to initialization request

### ISSUE THREAD

**Issue by mgrip** [Microsoft/language-server-protocol#354]
For large projects all under one source directory, it can sometimes be helpful to ignore certain filepaths or directories. Indeed most editors provide this functionality (usually in the form of glob patterns) to help with performance, or to hide diagnostic information for files that the user does not care about. This helps especially when dealing with third party libraries that are pulled into a project.

It could be helpful to allow clients to pass in patterns to have the server ignore certain filepaths, in addition to the `rootUri`

**Comment by laughedelic** [comment]
* I think that the language server (probably with the help of a build tool) should know better which files are relevant for the project and which aren't. So it should be some information in the initialization response from the server to the client which will take into account and won't send `didOpen`/`didChange`/etc. notifications for irrelevant files.
* It should be a combination of include & exclude patterns. For some languages/build tools it will be easier to say that all project sources are only under `src/` directory excluding `src/**/resources/`, for example.

**Comment by dbaeumer** [comment]
This is subject to the build system used by the programming language. For example a TS project is described in a tsconfig.json file which a TS language server reads and interprets. The protocol allows already for dynamic registration of open events. So after the server has read that file it should talk to the client and let him know that is is interested in the following files to be sync. The `DocumentSelector` that is used during the registration supports wildcards. So IMO there is no need for a ignored patterns in the initialization request. Adding this would even complicate things since it would require clients to read builds files which should normally only be interpreted by servers.

I will close the issue since I thing adding this is not necessary. Please ping if someone disagrees.
