### ISSUE TITLE
Please change Protocol Change Log format

### ISSUE THREAD

**Issue by lextm** [Microsoft/language-server-protocol#365]
It is a good idea to use `protocol-changelog.md` to track changes to the API surface. However, its current format can easily confuse readers.

For example, the first few sections use dates as title to organize the changes introduced. But the last section suddenly changes its title to a version number. Then how can a reader know what is the version for all the other sections?

I think the section title should all contain a version number, as well as the date it was published, which looks like this,

> 3.0.4 (11/27/2017)
> ------------------
> 
> 3.0.3 (11/24/2017)
> ------------------

This gives language server vendors (me included) a clear way to know which revision they are targeting, and then they can refer to release notes of an editor (or IDE) so as to see whether that revision is supported or not.

If we use Visual Studio Code as an example (well, bad example), [its 1.19 release notes](https://code.visualstudio.com/updates/v1_19#_language-server-protocol) says,

> Language Server Protocol
> --------------------------
> The language server protocol was extended with the following new feature: a completion context given access to the trigger character, more completion item and symbol kinds as well as markdown support for completion items and signature help. The protocol additions are available in the 4.0.0-next.x version of the client and server npm modules.

It would be much easier to say VSCode 1.19 supports LSP revision 3.0.4, than the vague statement above.

**Comment by dbaeumer** [comment]
We need to distinguish between the version of the LSP and the supporting npm modules. There version numbers are developing independently. For example the npm modules are at version 4.x (since we broke some API) however the LSP spec is still at version 3. Adding a version number to the LSP makes sense.

Regarding VS Code release notes. We only list this there since we don't want to publish another release note for the LSP. VS Code itself doesn't support the LSP out of the box. The LSP support comes through standalone npm modules maintained here: https://github.com/Microsoft/vscode-languageserver-node which then should refer to the LSP version number.
