### ISSUE TITLE
A method to retrieve a document buffer?

### ISSUE THREAD

**Issue by mickaelistria** [Microsoft/language-server-protocol#38]
Mainly for debugging purpose -seems like my invocations of didChange are not correct-, I'd like to retrieve the current state of the file for the language server. I didn't find a method to do that directly. Can one of the current operations be used for that?

**Comment by nadako** [comment]
This doesn't seems to be useful as a general langage server feature. For debugging, you can always introduce a custom request in your vscode plugin and send it from the language server.

**Comment by mickaelistria** [comment]
Note that the use-case here is not in the context of VSCode. I'm working on a LSP client inside Eclipse IDE, and such method would be helpful to make sure the code in Eclipse IDE and in Language Server are in sync (ie that I did send the right change events).

**Comment by dbaeumer** [comment]
@mickaelistria as @nadako correctly pointed out you can send a custom message. The language server protocol doesn't limit the messages you send. It simply standardize common used requests. If your server is used in different editors then your server has to deal with the fact that the client response with an error. Since the underlying protocol is JSON RPC you should receive a JSON RPC standard error code of -32601 which is MethodNotFound (see also http://www.jsonrpc.org/specification#error_object). 

I will close this issue since this shouldn't be part of the standard protocol. Pls ping if you feel otherwise.
