### ISSUE TITLE
CodeActionParams mandatory fields

### ISSUE THREAD

**Issue by amiramw** [microsoft/language-server-protocol#398]
Are all fields of `CodeActionParams` mandatory?
Or maybe exactly one out of `range` and `context` should be filled?

**Comment by rcjsuen** [comment]
@amiramw They are mandatory. Why would you send one without the other? Of course, nobody is preventing you from providing a `context` that has a zero length `Diagnostic[]`.

**Comment by amiramw** [comment]
Why do I need to provide range if I provided diagnostics? Should it be the same range as returned from the diagnostic?

**Comment by rcjsuen** [comment]
> Why do I need to provide range if I provided diagnostics?

The language server may return code actions that have nothing to do with the received diagnostics. Not all diagnostics are necessarily "easily" resolvable. The language server may instead just return some code actions for refactoring the code (such as extracting a function/method out of the selection).

> Should it be the same range as returned from the diagnostic?

No, you should be sending in a range that matches the editor's current text selection.

**Comment by amiramw** [comment]
Thanks, more questions...
- If I send code range and diagnostics then the LSP should return only commands relevant for fixing the diagnostics or also refactoring commands?
- With diagnostic sent and without text selection range sent, should the LSP server return diagnostic fixes or it must get some text selection range for that?
- If I send code range without sending the diagnostics (but there is one in that range) will I get fixes for the diagnostics?

**Comment by dbaeumer** [comment]
@rcjsuen thanks for the good answers you provide.

**Comment by rcjsuen** [comment]
@amiramw As far as I know, none of the questions you have asked are defined by the specification so feel free to take what I say with a grain of salt if you wish.

1. This is up to the language server to decide.

2. Same as above. Depending on what a code action will do, it may or may not require a valid text selection to do what it is designed to do. Perhaps the `range` contained within the `Diagnostic` itself will be sufficient, perhaps not. Note that since the `range` field is not optional, a language server may or may not throw an error if it detects that your client's JSON request does not conform to the LSP specification. A language server may also choose to outright ignore your request since it is not well-formed and just send back a zero length `Command[]` array. Please advance at your own risk.

3. Again, this is up to the language server to decide and sending in `null` or `undefined` instead of a zero length `Diagnostic[]` may cause problems per my second point above. Since the `CodeActionParams` of a `textDocument/codeAction` request includes a `TextDocumentIdentifier`, there is nothing preventing the language server from analyzing the file in question and figuring out what diagnostics are contained within the `range` you included in your request (if any).
