### ISSUE TITLE
documentLink/resolve has insufficient information in its request parameter

### ISSUE THREAD

**Issue by rcjsuen** [Microsoft/language-server-protocol#401]
Does anyone use or implement `documentLink/resolve`? I was going to implement this request but then realized that the single parameter of a `DocumentLink` in the request is not useful at all. The client may have three files opened in its editor and then asks the server to resolve a link. Then what? All the server has is a `DocumentLink` object with an arbitrary `range`. It is not possible for the server to figure out which of the three files the range is for so it can't even know what content string the range encompasses. Maybe it's `abc`, maybe it's `123`, maybe it's `http://github.com`, who knows?

Am I missing something here?

**Comment by dbaeumer** [comment]
@rcjsuen nice find. Points out no one every implemented it. We could do two things. Either add a resource to it so that the URI is known. Alternatively we can do the same as with the CompletionItem. That one has a data field that is preserved that lets the server to add information it can access on resolve. 

I actually tend to do the same for DocumentLink since it is a more flexible approach. The additional informaiton the server put in might not necessarily be the document. It might be something else.

**Comment by dbaeumer** [comment]
@rcjsuen do you want to look into this?

**Comment by rcjsuen** [comment]
@dbaeumer If we add a `data` field, is a new capability needed to state this similar to what you mentioned [here](https://github.com/Microsoft/vscode-languageserver-node/pull/332#issuecomment-379243203)?

**Comment by dbaeumer** [comment]
In principal yes. For this special case since it never worked I would argue we can leave it out.

**Comment by rcjsuen** [comment]
Closed by #464...
