### ISSUE TITLE
Question: what is the purpose of the willSave notification?

### ISSUE THREAD

**Issue by keyboardDrummer** [Microsoft/language-server-protocol#411]
It's not clear to me what an LSP server should do with a willSave notification. I'm asking because I'd like to know what the motivation is for a client to support sending this. Does receiving the notification mean that the server shouldn't start reading that file since it's about to be written to?

It's also not really clear what the latest time is a client may send this.

**Comment by dbaeumer** [comment]
The client only sends this if the server ask for such a notification. So it should only register for it if the server can do something with it. We add it to be consistent with willSaveWaitUntil and save.

The spec intentionally didn't specify the order between willSave and willSaveWaitUntil. However the event must be send before the save event.

Since the tool (editor) has the owner ship of a file when open the server is not allowed to read the file from disk. This is speced in the open / close document life cycle.

I close the issue opening that your questions are answered

**Comment by keyboardDrummer** [comment]
Dirk, thank you for the reply.

> We add it to be consistent with willSaveWaitUntil and save.

I interpret that as: when a client does not have a feature like 'format on save' and does not want to use `willSaveWaitUntil`, you allow the client to call `willSave` instead, so it can still make a `willSave` type of call. I see how that adds consistency.

However, to be honest I don't really see the validity of the consistency argument. It's still not clear to me what use-cases there are for this API. What is benefit the client gets from calling this?

I guess the real answer lies in how servers are responding to receiving this call. Do you happen to know more about that? If not then I might look into it at some point.

**Comment by dbaeumer** [comment]
There might be servers that can't implement incremental compiling on type and only recompile a file on save. In general know when a file gets saved is a useful information.

I agree that this can also be done with file events but the are usually more async then the will save notification.
