### ISSUE TITLE
Community: A place to discuss LSP

### ISSUE THREAD

**Issue by keegancsmith** [Microsoft/language-server-protocol#429]
Lots of people and companies are interested in LSP these days. There doesn't seem to be a place for the community to talk to each other outside of issues/PRs scattered around github. It would be great if there was an advertised place to hang out and discuss LSP with other members of this community. Something like a slack, discord or IRC.

Is there any interest in this?

**Comment by mickaelistria** [comment]
What would be the value of another channel?

**Comment by keegancsmith** [comment]
Is there a channel right now? If so it would be great if it was advertised. I'm just hoping for something more informal where I can directly engage with other people who are working with LSP.

**Comment by mickaelistria** [comment]
GitHub issues are a channel, just like a forum. 1 thread per issue, anyone can join. Most people working on LSP are expected to follow the issues here and receive notifications on questions.

**Comment by rcjsuen** [comment]
I could go either way on this.

While I too would like an informal place to just chat and chill, I appreciate the fact that this is the "only" place to go for all LSP-related discussions. This helps keep all the discussions and conversations in one place and thus easily searchable for anyone new to the community.

**Comment by dbaeumer** [comment]
I understand the need for an informal channel to for example ask questions. However discussion about the protocol itself should IMO happen in GitHub issues to have only one place where people need to go to.

**Comment by mickaelistria** [comment]
It's a feature request for GitHub to have different entry points for issues (bugs, enhancement requests) and question in the UI. But using issues with the "question" label is already not that bad.
It has some serious advantages: it transforms users into contributors much more easily because it's the same channel, and the other way round: contributors who follow the issues are better informed of users' question because they receive notifications for those equally to contribution discussions.
Several channels makes navigation from one to the other harder, scatters the community of users vs contributors when most project (and probably LSP) would like to keep both as close as possible one another.

**Comment by keegancsmith** [comment]
I feel I'd have more varied conversations with a wider range of people about LSP if it was in a more informal way. My personal feeling around the bar of filing an issue is much higher than random thoughts I may want to talk about in another sort of forum. I've been working on and with LSP related technology for roughly a year and a half and most of the conversations I have had have been internal about it. I've never really thought of Github issues as a great place to talk about LSP until an idea I have is more concrete. However, I'll start watching this repo and see if that changes.

**Comment by kdvolder** [comment]
> I feel I'd have more varied conversations with a wider range of people about LSP if it was in a more informal way. 

Actually this idea could backfire. I think that what may happen in reality is that you will get a 'less varied' number of people. Because, actually the people who are most knowledgeable about LSP and working on the spec, for example, might simply decide not to subscribe to the a informal channel where 'anything goes'.

So, yes, you might feel more comfortable just firing of a 'quick informal question' there, but the best people to answer your question may not be paying it much attention.

On the other hand, maybe you feel the 'bar' on github issues is a bit 'higher'. But perhaps that isn't really a bad thing. If you have a genuine question, and you put in a bit of thought and effort to phrase it well, there is no reason why you couldn't ask it here. And you probably have a better chance at getting a 'quality response'.

I mean... look at the varied responses you already got on this very question :-). It is working isn't it?

**Comment by dbaeumer** [comment]
Then lets try to not open another channel. @keegancsmith if you feel strongly about having that channel after testing issues, please ping. Then we can look into whether we could mimic the VS Code model.
