### ISSUE TITLE
When should a language server return a null response vs throw a Json RPC error?

### ISSUE THREAD

**Issue by gatesn** [Microsoft/language-server-protocol#439]
I wonder if you could provide some clarification on when a language server should return `null` vs returning a Json RPC error. For example, the `textDocument/completions`, `textDocument/definition` and `textDocument/symbol` requests all define `null` as a valid response. 

My interpretation right now is that if a language server does not _know_ if there are completions (e.g. it depends on compilation and compilation fails) then it should return null. 

But the `workspace/applyEdit` response goes slightly against this. It explicitly returns yes/no whether or not the edit was applied. Why doesn't it return null? Or throw an error?

**Comment by dbaeumer** [comment]
There is a little history to it. At the beginning the protocol didn't list `null` explicitly but it was allowed implicitly. So we made it from a specification point of view explicit. Regarding your questions:

- you should return a response error if for example the server itself runs into an exception since this is then signaled on the client side (e.g. the fact is logged). 
- you should return `null` if there wasn't a result. For example code complete was requested at a position where no completion is possible. An empty array is semantically equivalent. 
- `workspace/applyEdit` it would return a response error if the client run into an exception applying the edit. It returns false if the for example the document on the client side is already newer and the edits were rejected. We could have used `null` but then it would be harder to express the positive case. 

I will close the issue assuming that the explanation is sufficient. Please ping if not.
