### ISSUE TITLE
Getting Wild & Crazy with LSP

### ISSUE THREAD

**Issue by realisation** [microsoft/language-server-protocol#445]
I have a crazy thought I'm wondering how it fits in with LSP/if at all.

I am working on a project wherein I need to generate live program state via parsing. I'm making an IDE which will support these features. I only just started today thinking more sophisticatedly about that part of the project. 

What I'm wondering is, is it possible, and then what are the hurdles with, making the server side of the LSP implementation an actual running program, with a live network interface engaging frequently across the network, instead of something that is just for querying metadata on code being placed into files.

Please feel free to ask questions, I would really appreciate any insights into LSP that might save me time, or educate in general on parsing/IDE design. 

Also open/would appreciate referrals of other forums/chat rooms I could speak about these topics in.

**Comment by kdvolder** [comment]
That's not a crazy idea at all. 

> making the server side of the LSP implementation an actual running program

Well... duh. A server is a running program. What else could it be?

> with a live network interface engaging frequently across the network

Sure why not. A server is just a program that implements a specific protocol to comminicate with a client. As long as your server adheres to the protocol, how you implement the server and what it does 'under the hood' is really totally in your hands and under your control. You can implement the server in any programming language you like, for example (thouhg it will be easier if you choose a language for which someone already built a library to help you with that) and your server can do anything you want, including calling out to anything in the network, the internet. If you can write a program to do something, then you should be able to make your server do that, since yes, a language server is just another program. So whatever cool idea you have... go for it. The sky is the limit.

**Comment by realisation** [comment]
Well, double duh... I mean that it should do more than report meta data
about static code that doesn't do anything until you deploy it in a live
environment. The difference between a tool and an active application. I'm
not experienced in this area of IDE development, so probably some standard
things aren't in my head. I have literally used nothing but text wrangler
and vim so far.

Though I am getting a better understanding then of what LSP is.

There is probably a different implementation for each editor -- I wonder
how much what I'm going to be doing diverges from current clients of LSP
such that a new implementation would be required for each client.

**Comment by kdvolder** [comment]
Its a bit hard to get into your head and understand what you are thinking or trying to achieve. If you try to be a bit more concrete about what you want to achieve people might be able to give more concrete feedback.

So far all I get is you are asking 'can my server contact the network'. The answer is yes.

You also asked about needing different implementation per client.... Yes and no.

No... because if your server stays within the protocol it should work with any client **in theory**.

Yes... because... 

1. in practice not all clients are equal. And in practice we found the more complex your server or what you are trying to do, the more likely you'll run into some cases where you'll need to handle things slightly differently to work smoothly on different clients. So some bits of your server may have multiple implementations used for different client environments.

2. presently how you connect a client to server isn't standardized. Only the protocol on how client talks to server once a connection is establised is standardized. So for each client you care about, you will need to write some kind of a 'wrapper' to start the server and establish the connection.

3.  it depends really on what you are trying to do. If what you are doing involves some kind of fancy stuff on the client's ui that isn't covered by LSP protocol you will end up implementing some protocol extensions and this requires you to implement that fancy ui on each client you care about as well.

**Comment by realisation** [comment]
Nice, thank you that's very informative. I'm not 100% sure what I'm going
to require yet, it's going to take some experimentation as we implement
what we have built.

But it is time to start wrapping my head around the brass tacks of what
happens in a server. I wonder if that's best done here, or in a particular
LSP server repository.

I have questions all about how they work, so probably a specific one.
