### ISSUE TITLE
Standard for common configuration options

### ISSUE THREAD

**Issue by castwide** [Microsoft/language-server-protocol#452]
I'm in the process of adding configuration options to a [Ruby language server](https://marketplace.visualstudio.com/items?itemName=castwide.solargraph). I synchronized a configuration section based on the [example](https://github.com/Microsoft/vscode-docs/blob/master/docs/extensions/example-language-server.md). Right now I have a `solargraph.diagnostics` setting that enables/disables linting. I could add other settings like `solargraph.codeCompletion` and `solargraph.hover`, but wasn't sure if that was best practice. Is there a standard protocol for managing capabilities?

**Comment by dbaeumer** [comment]
@castwide actually we enhanced the way how a server can access configuration settings by making it a pull model instead of a push model (I need to update the documentation. Sorry for that. Created https://github.com/Microsoft/vscode-docs/issues/1610)

The pull model allows the server to define a set of settings it needs and the client needs to fulfill this settings model. An example can be found here where the server send a configuration request (https://github.com/Microsoft/vscode-extension-samples/blob/master/lsp-multi-root-sample/server/src/server.ts#L81) and the client fulfills it in its middleware (https://github.com/Microsoft/vscode-extension-samples/blob/master/lsp-multi-root-sample/client/src/extension.ts#L86) if there is no direct mapping to the client's settings store.

This gives the server the freedom to define its settings structure. 

But to answer your question: there is no standard since we thought it is not necessary. But may be it would be helpful to give some guidance in the spec about naming. 

Does that make sense?

**Comment by castwide** [comment]
@dbaeumer Some naming guidelines might be nice to have, but it's probably not a necessity. I just wanted to check if anything of the sort existed. I'm glad I did, since I wasn't aware of the pull model for configurations. Thanks for the explanation.
