### ISSUE TITLE
SignatureHelp.activeParameter

### ISSUE THREAD

**Issue by obfuscated** [microsoft/language-server-protocol#456]
I'm implementing a LS client and I'm wondering why activeParameter is inside the SignatureHelp object and not in the ParameterInformation object?

Currently I'm testing clangd as a server. This seems a bit limiting when dealing with C++ source code.

Here is an example:

```
int func1(const float a, float const b)
{
    return a + b;
}
int func1(const int b)
{
    return b*10;
}
int main()
{
    func1(|5, 6);
}
```
If cursor is at the | character and I request the textDocument/signatureHelp. I receive something like

```
{
  "id": 21,
  "jsonrpc": "2.0",
  "result": {
    "activeParameter": 0,
    "activeSignature": 0,
    "signatures": [
      {
        "label": "func1(const int b) -> int",
        "parameters": [ {"label": "const int b"} ]
      },
      {
        "label": "func1(const float a, const float b) -> int",
        "parameters": [ { "label": "const float a" }, { "label": "const float b" } ]
      }
    ]
  }
}
```
If I follow the spec I can highlight the parameter b in the first result, but not parameter a in the second result. Do I understand the spec correctly?

Can someone explain the rationale behind it? At least for C++ this seems a limiting. Probably for languages which support named parameters it might make a bit more sense, but still I think the language servers for such languages could fill the activeParameter for all of the found signatures without too much trouble.

Am I missing something?

**Comment by rcjsuen** [comment]
> If I follow the spec I can highlight the parameter b in the first result, but not parameter a in the second result. Do I understand the spec correctly?

@obfuscated In your example JSON response, VS Code will highlight `const int b` in the first result and `const float a` in the second result because `activeParameter` is set to `0`.

Are you seeing a different behaviour or am I misunderstanding something?

**Comment by obfuscated** [comment]
@rcjsuen I don't have VS Code installed to test it. But if it behaves as you describe it, then it is not following its own spec - https://microsoft.github.io/language-server-protocol/specification#textDocument_signatureHelp

> 	/**
	 * The active parameter of the active signature. If omitted or the value
	 * lies outside the range of `signatures[activeSignature].parameters`
	 * defaults to 0 if the active signature has parameters. If
	 * the active signature has no parameters it is ignored.
	 * In future version of the protocol this property might become
	 * mandatory to better express the active parameter if the
	 * active signature does have any.
	 */
	activeParameter?: number;

**Comment by rcjsuen** [comment]
@obfuscated Okay, I think I see what you are trying to say.

You mean that the specification is implying that `activeParameter` is **only** intended to be used for the "active signature" and not the other signatures in the `signatures` array, correct?

**Comment by obfuscated** [comment]
@rcjsuen Yes, this is how I understand it.

**Comment by dbaeumer** [comment]
@obfuscated good find. Actually I would like to loosen the spec around this a little bit since the `activeParameter` makes sense even for signature others than the active signature. Something like this: clients are free to use the `activeParameter` on signatures others than the active one if the client support for example scrolling through the signatures to highlight a given parameter. However there is no guarantee that the `activeParameter` is inside the range of `help.signatures[help.activeSignature].parameters`

**Comment by DanTup** [comment]
@dbaeumer I was just testing something here and noticed some strangeness... The LSP spec says if the value is not supplied or outside of the range then it defaults to 0. However, in VS Code if you set 0 then the first parameter is selected, but if you set -1 then no parameter is selected.

I would say this is a VS Code bug, BUT... I don't think it's appropriate to require this to be set. Imagine the following code:

```
test(a, b, c) {
  test(1, 2, 3, 4 /* invoke signature help here */ );
}
```

Based on the spec, you'd currently have to decide which parameter should be highlighted, when in reality none should, because there is no fourth parameter. I think that it should not default to 0 but be allowed to be missing, and the editor should show the parameters but not try to highlight one.
