### ISSUE TITLE
Compiling

### ISSUE THREAD

**Issue by jamiebuilds** [microsoft/language-server-protocol#470]
I'm working on [Parcel](https://parceljs.org) right now and we're looking into improving support for languages that need full program analysis in order to compile. In order to do this we're creating a plugin system that spawns servers for compilers and queries them as it packages modules.

We largely need it to do just these two things:

- Send files as we discover them (some of them may not be written to disk) to the server
- Request compiled output back from the server

We were hoping that language-server-protocol would cover a lot of this but it doesn't appear to have anything even related to code compiling.

Is that something this protocol would be interested in solving? It does make sense to me that the same server that is doing all sorts of program analysis would be able to also compile that code.

**Comment by ShaneDelmore** [comment]
This might be a better fit for https://github.com/scalacenter/bsp/blob/master/docs/bsp.md

**Comment by keegancsmith** [comment]
BSP looks interesting, thanks for the link. We (Sourcegraph) also need to solve parts of this problem, since to provide hover/j2d on a random repo commit often means building / fetching dependencies for the commit. Our approach is to wrap an LSP server with something we call a build server. The build server proxies the LSP requests, and potentially does work based on the TextDocumentURIs in the LSP requests. We mostly have written build servers targeting the popular build systems for each language we support. We haven't targeted a more general build tool like Buck/Bazel/pants/etc yet.

We also use a VFS abstraction, where the build server fetches file over LSP rather than expecting them to be on disk. (ie server asks the client for file contents over LSP).

**Comment by ShaneDelmore** [comment]
These are exactly the issues BSP is looking to help co-ordinate with LSP 💯

**Comment by dbaeumer** [comment]
I haven't read the BSP proposal in detail but I like the idea to have a separate protocol or kind of protocol extension to deal with this.

**Comment by jamiebuilds** [comment]
Happy to have this in a separate extension protocol. We were thinking of doing that anyways, so I'm glad to see someone is already thinking about it.

Is there anyone that works on BSP that would be willing to talk to the Parcel team about it? We've been looking at it, and we're not sure it covers everything we need.

**Comment by jvican** [comment]
I’m working full time on BSP and would be happy to chat about your use case. The protocol is purposefully designed to be language and build tool agnostic, so there are many open routes to collaborating with other organizations.

My short term plan is to gain more experience from implementing the protocol in jvm-based build tools (bazel, sbt, maven, etc) and refine the protocol as the implementation goes on. We focus on support for Scala and Java for now, but the protocol has the concept of “language extensions” so that other people can develop support for other programming languages.
