### ISSUE TITLE
Add DiagnosticTag Type

### ISSUE THREAD

**Issue by mjbvz** [microsoft/language-server-protocol#500]
VS Code recently added a [`DiagnosticTag`](https://github.com/Microsoft/vscode/blob/83625fa9cbbdec3eab4a635c62f88aab0929aa80/src/vs/vscode.d.ts#L3945) type for attaching additional metadata to a diagnostic. These tags can be used by editors to control the presentation of diagnostics. See https://github.com/Microsoft/vscode/issues/51104 for a discussion of this

Currently only one tag type has been added on the vs code side: `DiagnosticTag.Unnecessary`. This tag makes diagnostics for unused variables or unreachable bits of code. VS Code renders code marked with `DiagnosticTag.Unnecessary` as faded out. 

`DiagnosticTag` only adds metadata to a diagnostic and should not break clients that do not support it. With `DiagnosticTag.Unnecessary` for example, clients that do not support tags will still receive standard diagnostics for unused variables and can render them as regular errors / warnings / suggestions

**Comment by dbaeumer** [comment]
This is more complicated for the LSP. Since the LSP is implemented for different clients simply adding this without thinking about how it will be implemented on other clients is not what we should do. We at least do need flag this as a client capability. BTW: this is why I was not a big fan of adding this that way.

**Comment by dbaeumer** [comment]
Another thing we need to consider is that Diagnostics flow in both ways. So even if a client doesn't handle a `DiagnosticTag` we need to spec that the client tries to preserve the information when a diagnostic object is send from the client to the server in a code action request.

**Comment by mjbvz** [comment]
Clients that do not support `DiagnosticTag` should still be able to consume the diagnostics, they just will miss out on the special rendering of those tags. For example, TS sends all unused variable as suggestion level diagnostics. A client that does not know about `DiagnosticTag` will render them as normal inline suggestions

**Comment by dbaeumer** [comment]
I agree, but the problem I have in the LSP are objects that flow in both ways and the fact that the LSP tries to work in a backwards compatible way and for different client implementation. So in general that means:

- if we had a enum, tag value client announce there supported value set to avoid that server do compute `expensive` values which the client drops anyways.
- if an object flows in both ways then we need to let the server know if the client preserves the values even if he doesn't honor them. Assume that a server generates a diagnostic with a tag and the diagnostic comes back to the server without that tag in a code action request the server might be surprised. 

This is all not an issue with the VS Code API since we have strict versioning which due to the loose Eco system of LSP we tried to avoid (btw debug does the same there with its protocol). So whenever we add `language` API to VS Code I try to do that in a way that makes it not too hard to support in LSP.

**Comment by rcjsuen** [comment]
Looks like this got added into `vscode-languageserver-node`.

See https://github.com/Microsoft/vscode-languageserver-node/issues/477.

**Comment by KamasamaK** [comment]
Pending PR is #645

**Comment by dbaeumer** [comment]
Yes, but only in a next version so far.

**Comment by dbaeumer** [comment]
Updated spec on dbaeumer/3.15 branch.
