### ISSUE TITLE
Rich diagnostics extension

### ISSUE THREAD

**Issue by michaelcfanning** [microsoft/language-server-protocol#502]
What thinking has previously been done here? The OASIS SARIF technical committee has released a public draft of a common interchange format for transporting rich diagnostics results. This format can include complex paths through functions, associated data state at specific thread flow locations, graph representation/traversals of code, stack-based reporting, as well as simple, user-facing string diagnostics.

This format/mechanism is particularly useful for tools that run out-of-band due to the costs of analysis. For these scenarios, it is interesting to think about an end-to-end results management protocol that would allow an editor to 'connect' to a result store or otherwise associate a sidecar repository of results with code that is currently under development. The end-to-end lifecycle of a diagnostic pulls in other complex topics such as bug filing, annotating results as false positives, won't fix for other considerations (such as a tool firing against test code), or as low quality (the result is not actionable, is poorly described, etc.). 

Discussed previously? I've looked in issue history and haven't uncovered any obvious prior conversation.

https://github.com/oasis-tcs/sarif-spec/

**Comment by dbaeumer** [comment]
@michaelcfanning thanks for the pointer. No, we never discussed that spec in the LSP land. One thing to keep in minds is that the LSP is a UI driven protocol not a program structure driven protocol. So for diagnostics we added information that is usually presented to a user in the UI and no information that will allow a client to interpret the diagnostic. This is basically true for all the results returned from a LSP server.

**Comment by dgmelski** [comment]
I am very interested a protocol for connecting analysis tools, results managers, and viewers. We have been working with @michaelcfanning on a viewer for SARIF in VS Code. 

I think there's an opportunity to incorporate SARIF in LSP in a way that would allow LSP clients to present more static analysis results. For example, @michaelcfanning mentioned "code flows." These are expressed as a sequence of code regions, which are expressed using offsets in source files --- which I think is similar to LSP. SARIF also uses JSON, though unfortunately the code regions are expressed slightly differently.

If diagnostic reports could include SARIF (or at least code flows) they be visualized in LSP clients, as we're demonstrating in our VS Code plugin. That's one example. There is plenty of other interesting information in SARIF.

I think down the road, we will want a "Static Analysis Server Protocol (SASP)" that cannot be a simple extension to LSP. For example, an LSP server seems more like a plugin than a true server that can have multiple simultaneous connections. Still, maybe SASP could use LSP as a subcomponent, or maybe making a client that handles LSP+SARIF would be a stepping stone to making a client that handles SASP?

Perhaps a demo of the SARIF viewer would be helpful?

**Comment by michaelcfanning** [comment]
Repeating a bit of David's content here. SARIF as a format is intended to help drive rich UI experiences for the range of static analysis results. And so, as David notes, this might include packaging path-through-function data that helps illustrate a presumed code path through a function that leads to a quality problem. An editor such as VS Code might usefully colorize source files to help drive investigation. As another example, some tools may persist stack information as part of a diagnostic. For this case, an IDE such as visual studio might populate its stack window and enable a navigate-to-code experience on clicking an individual frame - again, in support of investigation a potential quality defect.

The examples above are strictly UI/viewer experiences. We have a SARIF Visual Studio add-in that represents a start on providing useful investigation capabilities. We have a SARIF VS Code extension for the same scenario.

There is an interesting broader scenario to consider whether we can codify a protocol for managing a store of static analysis results, that might be consumed by multiple clients simultaneously, who are attempting to push these results through their disposition life-cycle (i.e., trying to investigate issues, drive fixes for true positives, permanently suppress false positives from future consideration, etc.). This life-cycle could be very complex, entail filing work items, drive an exception process for ignoring a security relevant concern, attempt to kick off a rerun of a tool to verify whether a proposed fix succeeds.

Based on David's post and the above, I wonder what your feedback is? Where are the limits of what might make sense here to address via a proposed LSP extension? Where are the clear limits you perceive in LSP's purpose that would argue for defining something altogether separate (a SASP as David has termed it).

**Comment by mickaelistria** [comment]
> I think there's an opportunity to incorporate SARIF in LSP in a way that would allow LSP clients to present more static analysis results.

As an implementor of an LSP client, I don't think there is need nor wish for more structured complexity so far, and I'd rather not have to implement this complex standard in the default LS client.
However, I think it would be interesting for experimental purpose at the moment to try SARIF in some LSP servers/clients. Rather then using the default `textDocument/publishDiagnostics` and `Diagnostics` elements, you could create a language server which would also include operations such as `sarif/publishDiagnostics`, `sarif/codeFlow`... and extend the clients to also support and use those new elements.
I think that as long as there are no good examples of SARIF working on multiple LSP servers and clients, the integration cannot be perceived as mature enough and the value as high enough to standardize it in LSP. If after some successful demos there is a wider interest in SARIF from the LSP community, then it can be considered as an "official" extension in the spec, or even have dedicated elements integrated in the model.

> we will want a "Static Analysis Server Protocol (SASP)" that cannot be a simple extension to LSP. For example, an LSP server seems more like a plugin than a true server that can have multiple simultaneous connections. 

That's I think where things diverge with LSP. As @dbaeumer mention, the LSP is UI-based and doesn't really care about what's happening under the hood: is this compilation, is this parsing, is this static analysis, is this dynamic analysis, is this test execution, is this just someone in the internet typing content and annotating your code on the fly... It simply thinks in term of what you want to show your user while editing code in the general case.
I think static analysis fits very well in LSP if you want to render the results as diagnostics, quickfixes, hovers, completion...
So if you want the LSP to serve SARIF better, rather than focusing on the format of the SARIF content and put in in the LSP, it would be more interesting to consider what kind of UI you need to express SARIF results to the end-user in an IDE and what's missing in LSP to express this UI.
SARIF could be a way to do a language server (basically one could create a LS that can turn any SARIF report into a set of LSP concepts to user and this would be generic). As far as I understood so far, SARIF is a technology that would make more sense in the language server implementation side than in the protocol or in the client.

**Comment by mickaelistria** [comment]
> I think there's an opportunity to incorporate SARIF in LSP in a way that would allow LSP clients to present more static analysis results.

As an implementor of an LSP client, I don't think there is need nor wish for more structured complexity so far, and I'd rather not have to implement this complex standard in the default LS client.
However, I think it would be interesting for experimental purpose at the moment to try SARIF in some LSP servers/clients. Rather then using the default `textDocument/publishDiagnostics` and `Diagnostics` elements, you could create a language server which would also include operations such as `sarif/publishDiagnostics`, `sarif/codeFlow`... and extend the clients to also support and use those new elements.
I think that as long as there are no good examples of SARIF working on multiple LSP servers and clients, the integration cannot be perceived as mature enough and the value as high enough to standardize it in LSP. If after some successful demos there is a wider interest in SARIF from the LSP community, then it can be considered as an "official" extension in the spec, or even have dedicated elements integrated in the model.

> we will want a "Static Analysis Server Protocol (SASP)" that cannot be a simple extension to LSP. For example, an LSP server seems more like a plugin than a true server that can have multiple simultaneous connections. 

That's I think where things diverge with LSP. As @dbaeumer mention, the LSP is UI-based and doesn't really care about what's happening under the hood: is this compilation, is this parsing, is this static analysis, is this dynamic analysis, is this test execution, is this just someone in the internet typing content and annotating your code on the fly... It simply thinks in term of what you want to show your user while editing code in the general case.
I think static analysis fits very well in LSP if you want to render the results as diagnostics, quickfixes, hovers, completion...
So if you want the LSP to serve SARIF better, rather than focusing on the format of the SARIF content and put in in the LSP, it would be more interesting to consider what kind of UI you need to express SARIF results to the end-user in an IDE and what's missing in LSP to express this UI.
SARIF could be a way to do a language server (basically one could create a LS that can turn any SARIF report into a set of LSP concepts to user and this would be generic). As far as I understood so far, SARIF is a technology that would make more sense in the language server implementation side than in the protocol or in the client.
