### ISSUE TITLE
Richer provenance for Diagnostic messages

### ISSUE THREAD

**Issue by shaded-enmity** [microsoft/language-server-protocol#519]
Currently each `Diagnostic` message provides a `source` field, which is supposed to identify the particular LSP that emitted that message. The problem is when the data for the LSP are provided by 3rd parties.

Example:

The https://github.com/redhat-developer/vscode-yaml/ extension provides means for validating & completing YAML files based on JSON schemas. The schemas can be local, or remote (schemastore.org etc.) - which brings up an interesting problem, while the `source` of the message is definitely the `vscode-yaml` extension, the decision whether or not to emit the diagnostics was, however, based of off data provided by a 3rd party. This creates a huge mess for people trying to report errors because they see the `source` as being `vscode-yaml` whereas the error should really be reported against the actual schema provider.

There are solutions that would not require any changes to the LSP (change the `source` field, or emit a one-off diagnostics stating 'Report errors at: ...', etc.) so I'd love to know what others think about this.

**Comment by dbaeumer** [comment]
If you add this to the message then it should be post fixed. Otherwise it makes it very hard to read theses messages. And the source field should point to the extension providing the diagnostics.

**Comment by ssbarnea** [comment]
I think that we need an additional optional field that can pinpoint to the "most appropiate" issue tracker for that issue. This would allow meta-validation tools like vscode-yaml to provide more information that  can help user debug the problem and eventually fix it at the source.

If we start appending this information to the normal message it would clutter the user interface because for the majority of the reports the issue is with the file, not the tool users to validate. Still, for those few that recognize a broken validation schema, we need to be able to give them a direction regarding where to report the issue.

If this does not happen, tools that are using (lots of) schemas defined in other places would endup being flooded by false bug reports.

**Comment by dbaeumer** [comment]
One idea would be to use related diagnostic information for this to point to the schema that generated the error.

**Comment by shaded-enmity** [comment]
that sounds interesting @dbaeumer I guess we could use the uri property of Location to point to some landing page of the schema, I reckon that pointing to the schema directly would be confusing for end users.

One question though, reading through the discussions in the RelatedDiagnostics issue it seems that it is expected that the uri will point to some local location, do you know of its well supported to provide an actual uri to a web page?

**Comment by dbaeumer** [comment]
I think it would be fine to use uri different than `file:`. But let me check.

**Comment by shaded-enmity** [comment]
Hi @dbaeumer did you have a chance to check the semantics of `uri`? Thanks

**Comment by dbaeumer** [comment]
I check that the URI can be a non file URI. However it requires the client to handle these URI's since the LSP has no support for content providers. So if you have a URI with a scheme 'abc' the client needs to be able to handle the scheme and provide the content if the user for example clicks on it in the problems view. VS Code has support for custom URI handlers.
