### ISSUE TITLE
Namespace ''vscode'' has no exported member 'DocumentSymbol'.

### ISSUE THREAD

**Issue by YongdongHe** [Microsoft/language-server-protocol#556]
![image](https://user-images.githubusercontent.com/9399699/44640990-66b5b200-a9f7-11e8-8a0b-31b579d09d16.png)

**Comment by YongdongHe** [comment]
vscode  has been update to newest

**Comment by rcjsuen** [comment]
@YongdongHe Please share your `package.json` file here.

**Comment by dbaeumer** [comment]
You need to move your engine field in the package.json to `^1.26` and run `npm run update-vscode`. The latest VS Code client needs the latest VS Code version.

In general this should be filed / discussed in `vscode-languageserver-node` repository since it has nothing to do with the specification itself.
