### ISSUE TITLE
Introduce CodeLens notification message: `‘textDocument/publishCodeLenses’`

### ISSUE THREAD

**Issue by BoykoAlex** [Microsoft/language-server-protocol#557]
It'd be great if `‘textDocument/codeLens’` message was a notification rather than request/response type of message. Push model might be better than pull model. Suppose CodeLens info is coming from a third-party process, i.e. a running application. Hence, trigger to pull new CodeLenses is out of control really...

Think `‘textDocument/publishCodeLenses’` notification message would be great and more versatile than the request/response message. Any chance this message can be introduced? Perhaps along with the request/response message rather than instead of it?

**Comment by martinlippert** [comment]
The use case for this on our end is a code lens that could appear and change over time.

**Comment by dbaeumer** [comment]
What we need to introduce is a codeLens change notification from the server to the client so that the client can re-pull.

From the experiences we have so far a pull model from the client to the server superior especially since the client can decided when it is the best time to pull (consider a tab goes to the background and has stale code lens information. The client can postpone the pull until the tag gets visible again). And the client could include view port information to only compute necessary parts. It puts a little bit more management code onto the server but overall we found it the better strategy.

**Comment by dbaeumer** [comment]
Actually dups: https://github.com/Microsoft/language-server-protocol/issues/358
