### ISSUE TITLE
Allow format response to specify location of cursor

### ISSUE THREAD

**Issue by octref** [microsoft/language-server-protocol#573]
Currently, when running format operations, if it returns a huge `TextEdit` that replaces the whole file, the cursor gets set to the end of that `TextEdit` in VS Code.

It would be good to allow the server to send back an `offset`, so the client can set the new cursor position correctly. Prettier even has an API for this: https://prettier.io/docs/en/api.html#prettierformatwithcursorsource-options.

**Comment by dbaeumer** [comment]
The LSP (except for snippets) stayed so far away from letting the server control the position of the cursor since this is IMO something the editor should control. And I still think that this is the right approach. Sending huge edits is not only bad for the cursor it also will delete breakpoints and other markers. This is why we encourage to send many small edits.

For VS Code itself I know that the format code will if it is only a huge edit replacing the full content do a diff behind the sciences and execute little edits. So if this happens there might be something wrong with the smart logic in VS Code?

I tend to close this is as something we will not implement.

**Comment by LaurentTreguier** [comment]
I had the same problem with a formatting library I was using. I implemented a simple diff algorithm to detect which part of the text had actually changed between the original document and the formatted one. As it turns out, it was not too hard to do, and mitigates the problem very well. This would probably prove a better solution than changing the protocol.

**Comment by octref** [comment]
> For VS Code itself I know that the format code will if it is only a huge edit replacing the full content do a diff behind the sciences and execute little edits. So if this happens there might be something wrong with the smart logic in VS Code?

I'll try to get a repro.

@LaurentTreguier What diff library are you using?

**Comment by LaurentTreguier** [comment]
@octref Although I first thought of using a library to do this, I ended up [implementing it myself](https://github.com/d-language-server/dls/blob/97de62ec46920ef14742d71d5d99ea243d150072/source/dls/tools/format_tool.d#L164) instead. It's less than 100 lines long (including blank lines and lines containing only braces), and its logic is simple but sufficient for this.
