### ISSUE TITLE
Set of base methods every server must support

### ISSUE THREAD

**Issue by raja-s** [Microsoft/language-server-protocol#599]
From the current spec:

> Capabilities that existed in the 2.x version of the protocol are still mandatory for clients. Clients cannot opt out of providing them. So even if a client omits the ClientCapabilities.textDocument.synchronization it is still required that the client provides text document synchronization (e.g. open, changed and close notifications).

So all client capabilites from version 2.x are mandatory for an LSP client implementation. What about LSP servers? Is there a place in the spec/docs listing all mandatory methods that a base implementation of an LSP server must support?

**Comment by rcjsuen** [comment]
@raja-s I feel like the only minimum requirement would be to honour a `initialize` request. I'm not sure what other requests or notifications should be considered a hard requirement...

**Comment by raja-s** [comment]
Yeah I couldn't find any part of the spec describing such hard requirements, so I thought maybe someone from the protocol designers could clear that up.

**Comment by kdvolder** [comment]
It seems like a somewhat odd question. Except for the 'initialize' request, as a server implementor you basically have to 'opt in' to pretty much everything else. And as a server implementor you will start from the functionality that you want to support for your language, then you will opt-in to implementing some part of the protocol to make that happen.

For example, if you wanted content-assist for your language you declare your server to the client as a 'completion provider' and then implement something to handle completion requests.

I haven't scanned the whole protocol document to look for exceptions, but I think that is the typical workflow. 

So I think a minimal language server really just has to implement handling intialize and nothing else.

Such a language server wouldn't be very useful because it basically does nothing from a user's point of view (no completions, no linting, no code actions etc.).

**Comment by raja-s** [comment]
Alright, thank you both :) Closing this issue.

**Comment by dbaeumer** [comment]
@kdvolder absolutely correct. 

@raja-s the sentence you are referring to are client capabilities which got introduced in version 3.x. In 2.x clients needed to support some basic capabilities and they are still mandatory. In 3.x all new client capabilities (for example to apply workspace edits) are optional and a client needs to signal in the initialize request which capabilities it supports.
