### ISSUE TITLE
Clarification needed for DidChangeWatchedFiles Notification

### ISSUE THREAD

**Issue by natgabb** [Microsoft/language-server-protocol#60]
When exactly should this notification be sent? Will this notification with a file marked as `FileChangeType.Changed` always be sent alongside a [DidChangeTextDocumentNotification](https://github.com/Microsoft/language-server-protocol/blob/master/protocol.md#didchangetextdocument-notification)? Or should the DidChangeWatchedFiles Notification with a `FileChangeType.Changed` only be sent for changes to files made outside of the language server? As in, when we get a DidChangeWatchedFiles we should reset the files we are watching because they have changed externally.

**Comment by akosyakov** [comment]
@natgabb I assume that:
1. DidChangeWatchedFiles notification is sent when physical files belonging to the workspace are created, changed or deleted, regardless to open documents;
2. DidChangeTextDocument notification is sent when a content of an opened document was changed;
3. a document can correspond to a physical file, but not necessary, e.g. if you are working with in memory model, so if it does correspond then only after saving the document you will get DidChangeWatchedFiles notification since it will flush changes to a file on the disk.

What do you mean by "made outside of the language server"?

**Comment by dbaeumer** [comment]
@natgabb @akosyakov answer is correct. There is one thing to add that is documented in the protocol as well. The open/change/close text document life cycle has implication on the ownership of the content of a file as well. If a document is opened then the ownership of the content of that document belongs to the editor. The server SHOULD never rely on the content on disk for open documents. If a document is closed the server is allowed to read the document from disk.

I am closing the issue since IMO everything is answered. @natgabb please ping if you think otherwise.

**Comment by natgabb** [comment]
@dbaeumer @akosyakov Thank you for the answers. I have two more questions:

1. If you receive a `DidChangeWatchedFiles` notification on a file for which you previously received an `FileChangeType.Open` event and some `FileChangeType.Changed` events (but no close event), what is the expected behavior? Flushing changes made by the editor (i.e rereading the contents from disk)?
2. I'm not sure if I understood the answer fully, so here is a clearer question: For any given `FileChangeType.Changed` event, will there be a corresponding `DidChangeWatchedFiles` notification?

If my understanding is correct and we do indeed flush "unsaved" editor changes when we receive `DidChangeWatchedFiles` then it follows that we would not send a `DidChangeWatchedFiles` notification with a `FileChangeType.Changed` event.
