### ISSUE TITLE
How do I use tcp/socket?

### ISSUE THREAD

**Issue by DKPN** [Microsoft/language-server-protocol#604]
Sorry I'm somewhat new. I spent roughly two hours looking at source code and I can not figure it out. In the lsp example https://github.com/Microsoft/vscode-extension-samples/tree/master/lsp-sample I see 'TransportKind.ipc'. With digging I see TransportKind.socket is an option but for the life of me I can't figure out how to pass in the socket address+port. I tried looking at documentation, source and searching the web.
I took a look at other projects and they appear to be using standard in and out. I wrote `serverModule = "absolute/path/to/binary.exe"` and change ipc to TransportKind.stdio. I suspect it's being loaded as a node script. I see the error

> .exe:1
> (function (exports, require, module, __filename, __dirname, process, global, Buffer) { return function (exports, require, module, __filename, __dirname) { MZ�
>
> SyntaxError: Invalid or unexpected token

I suspect there's an option to launch it as a binary/shell but I don't see it. I tried searching other projects on how they launch their server but I don't see anything

My server is written in C++. I don't think I'll need any rpc json code. At the moment I simply want to see the incoming request.

**Comment by LaurentTreguier** [comment]
Same here. From what I've seen it looks like sockets are only supported for node modules, and anything else can only use stdin/stdout.
Maybe this issue should be on the [vscode-languageserver-node](https://github.com/Microsoft/vscode-languageserver-node/issues) repo though, since it's an implementation issue

**Comment by cdietrich** [comment]
You May have a look here https://github.com/itemis/xtext-languageserver-example/blob/master/vscode-extension/src/extension.ts

**Comment by LaurentTreguier** [comment]
@DKPN I have an example here for using stdio: https://github.com/d-language-server/vscode-dls/blob/master/src/extension.ts#L94. Minus the `client.onReady()` part, it should give an idea, it's mainly just about using the `Executable` interface.
@cdietrich nice, that clears things up for me!

**Comment by DKPN** [comment]
@LaurentTreguier thanks. Writing `serverOptions = {command:"path\\to\\test.exe"};` got me on track.

**Comment by dbaeumer** [comment]
IPC can only be used with node modules since it is a very specific communication mechanism for node. All other can be used with every language. What needs to be understood is that for connection timing issues the server is actually a client and the client is the server in terms of opening the ports.

When you specify a socket transport the client is listening on that port for a connection. The socket port number is passed as `--socket=${port}` to the server process started.

I am closing the issue. Please ping if something is still unclear.
