### ISSUE TITLE
Opt-in list of supported CodeActionKind isn't convenient

### ISSUE THREAD

**Issue by mickaelistria** [Microsoft/language-server-protocol#620]
I've made some changes in Eclipse LSP4E so it supports the CodeActionKind.
I'm quite skeptical about it, at least in how it's described in the specification as it requires some effort from every client to support a new kind, while there seems to be no need for it. Indeed, independently of the kind, a CodeAction remains a WorkspaceEdit or a Command, and this is true for any existing or future kind so far. So once a client supports WorkspaceEdit or Command, what it the value of asking client about kind CodeActionKinds it supports? And that means that every time a new codeActionKind is identified, all clients would need to adapt although it requires actually no workflow change?
I think it'd be good to find a way to declare compliance with all/any CodeActionKind in the client instead of forcing them to list all CodeActionKinds.

**Comment by dbaeumer** [comment]
The is actually not an opt in list. The code actions kinds can be used by the client to group things in the UI (e.g. put code actions into a special refactoring menu) if the client has one. 

The client capability is speced like this:

```
* The code action kind values the client supports. When this
* property exists the client also guarantees that it will
* handle values outside its set gracefully and falls back
* to a default value when unknown.
```

So servers are allows to send kinds which the client doesn't know but it needs to handle gracefully. However the server can use some kinds the client support to for example tag things as source or refactoring actions.

Forcing compliance is IMO hard to achieve here since it is more a UI think which I didn't want to standardize on.

Anything that is unclear?
