### ISSUE TITLE
Syntax highlighting support

### ISSUE THREAD

**Issue by ibuziuk** [Microsoft/language-server-protocol#682]
Syntax highlighting is currently out of scope of the LSP specification. This means that syntax colouring is still provided internally by IDE (e.g. xtext for Eclipse IDE) and there is no unified / standard way for providing default syntax scheme as part of language server. The proposal is to provide some specification in LSP in order to make  syntax highlighting a part of the protocol. The most trivial implementation might be hex-based e.g.

```
"const" : "#00ff00" // green
"for" : "#0000ff" // blue
"int" : "#ffff00" // yellow
```

**Comment by ibuziuk** [comment]
oh, probably a duplicate of https://github.com/Microsoft/language-server-protocol/issues/513

**Comment by mickaelistria** [comment]
FWIW, Eclipse IDE supports TextMate grammars, so do most other tools these days. XText could.consoder generating a Textmate grammars for its DSL to have portable syntax highlighting.
While syntax highlighting would make some sense in the protocol, textmate grammars are a decent enough workaround to not make it high priority.

**Comment by ibuziuk** [comment]
well, it looks like there are already a few LSP related issues opened which indicates traction for making syntax highlighting a part of the protocol:
- #513
- https://github.com/autozimu/LanguageClient-neovim/issues/383

**Comment by dbaeumer** [comment]
I will mark this as a dup of https://github.com/Microsoft/language-server-protocol/issues/513 since having this will allow syntax highlighting as well (and we will not have two different approaches).

In general it is our expierence that syntax highlighting must be fast and it best done inside the editor itself. So requesting this from the server might not be optimal.
