### ISSUE TITLE
Add a note about how to handle (reject?) requests after a shutdown notification

### ISSUE THREAD

**Issue by DanTup** [Microsoft/language-server-protocol#684]
After a shutdown notification (but before the exit notification) presumably a server should reject further requests, but this isn't currently mentioned in the spec. I've implemented it this way and also added my own error code for it, but like there's a `ServerNotInitialized` error code in the spec, maybe there should also be a defined error code for `ServerShuttingDown`?

**Comment by dbaeumer** [comment]
Specing this is definitelly a good idea. I would not defined a error code for it since this is not a very likely situation and nothing the client can recover from (especially since the client caused this). I would simply say we error with `InvalidRequest`.

Side node `ServerNotInitialized` is a JSON RPC error code not a protocol error code which we would need to define for `ServerShuttingDown`
