### ISSUE TITLE
Allow empty WorkspaceSymbols query, or support wildcard

### ISSUE THREAD

**Issue by mickaelistria** [microsoft/language-server-protocol#740]
While it might not be recommended for performance reason, it would still be profitable for some cases to allow to list workspace symbols without a specific query.
I think the query in workspace symbols could be omitted or empty. Currently, the spec says "non-empty" and doesn't mention the value to pass for "all symbols".

**Comment by rcjsuen** [comment]
Also see:

- #13 
- #307 
- #687 
- https://github.com/Microsoft/vscode-languageserver-node/issues/458

**Comment by DanTup** [comment]
Based on the comments in https://github.com/microsoft/vscode-languageserver-node/issues/458 and the fact that VS Code sends empty strings, I think the fix will be to remove the non-empty comment from the spec. I've opened [a PR for this ](https://github.com/microsoft/language-server-protocol/pull/770) but hopefully @dbaeumer can confirm.

(I think it's fairly safe to send an empty string for now, since VS Code does it, so it's almost certain that other servers will support it).

**Comment by dbaeumer** [comment]
Changed spec to allow empty string. Is in branch 3.15.
