### ISSUE TITLE
What is output of Hover when it is an array?

### ISSUE THREAD

**Issue by mtangoo** [microsoft/language-server-protocol#773]
I was testing LSP against felixbecker/php-language-server and I found that it retuns array in content part. But am not sure if the format is correct. It have keys language and value that I cannot find in the protocol. Can anyone confirm that this request is Spec compliant? We want to write a spec compliant client.

Sorry if it was asked and clarified already.

Here is request
```
{
  "id": 9,
  "jsonrpc": "2.0",
  "method": "textDocument/hover",
  "params": {
    "textDocument": {
      "uri": "file:///path/to/file"
    },
    "position": { "line": 103, "character": 25 }
  }
}

```

and here is respective response

```
{
  "result": {
    "contents": [
      { "language": "php", "value": "<?php\nclass ClassName extends ParentName" },
      "This is the model class for table \"tableName\"."
    ],
    "range": {
      "start": { "line": 103, "character": 22 },
      "end": { "line": 103, "character": 27 }
    }
  },
  "id": 9,
  "jsonrpc": "2.0"
}
```

**Comment by Aerijo** [comment]
It is compliant; [the spec](https://microsoft.github.io/language-server-protocol/specification#textDocument_hover) says to expect a `MarkedString`, an array of `MarkedString`, or a `MarkupContent`. The client needs to work out which it is; that information is not part of the protocol (e.g., if it is an array, assume it is an array of `MarkedString`).

The next line defines a `MarkedString` to be a `string`, or an `object` with `language` and `value` properties.

Presumably, the `language`-`value` form is so the client can apply syntax highlighting (if possible). So that response should look something like how the following markdown would render
````
```php
<?php
class ClassName extends ParentName
```
This is the model class for table "tableName".
````
_______
```php
<?php
class ClassName extends ParentName
```
This is the model class for table "tableName".

**Comment by dbaeumer** [comment]
@Aerijo thanks for providing the answer!

One additional thing: we encourage people to use `MarkupContent` in favour of `MarkedString` / `MarkedString[]`. Reason is that it provides more capabilities since it supports markdown content. However not all clients need to support this. It is driven by capability flags.

**Comment by mtangoo** [comment]
Thanks @Aerijo and @dbaeumer 
That's clear now
