### ISSUE TITLE
Clarifaction of empty completionProvider in ServerCapabilities

### ISSUE THREAD

**Issue by nemethf** [microsoft/language-server-protocol#830]
I understand that if completionProvider is missing from ServerCapabilities, then the server does not support completion.  But can you, please, confirm that the following two examples of SeverCapabilites are equivalent and they mean the server does support completion?  And therefore the server cannot explicitly state that it doesn't support completion.

example 1: `{"completionProvider": { "resolveProvider": false,  "triggerCharacters": []  }}`

example 2: `{"completionProvider": {}}`

Thank you.

**Comment by dbaeumer** [comment]
@nemethf yes they both should register a completion provider on the client side. Do you see issues with this?

**Comment by nemethf** [comment]
What you wrote is logical and that is what we expected.  I was unsure about the answer probably because I find the standard doesn't completely consistent:  
```
completionProvider?: CompletionOptions;
codeActionProvider?: boolean | CodeActionOptions;
```
I didn't understand why completionProvider wasn't defined as: `completionProvider?: boolean | CompletionOptions;`

But I guess it doesn't really matter. Thank you again.

**Comment by joaotavora** [comment]
@dbaeumer what about `{"completionProvider": null}`? Is this legal at all? I'm hoping you say "no", btw.

**Comment by KamasamaK** [comment]
I hope so too. My understanding is that the types listed are exhaustive. So unless `null` is explicitly mentioned as a type, it's not valid. Given the TypeScript declarations, I imagine the compiler has `strictNullChecks` enabled.

**Comment by dbaeumer** [comment]
> I didn't understand why completionProvider wasn't defined as: completionProvider?: boolean | CompletionOptions;

Legacy and compatibility :-)

`{"completionProvider": null}` will not register a completion provider and is even invalid since `null` is not listed as a valid type.

**Comment by felixfbecker** [comment]
> {"completionProvider": null} [...] is even invalid since null is not listed as a valid type.

@dbaeumer this seems to contradict an old comment from you: 

> @felixfbecker we do treat undefined and null 'equal' in the protocol.I even think that I state somewhere that you should send null not undefined since undefined doesn't exist in other languages. On our server side we even have code that explicitly exchanges undefined with null. And the client code always treats undefined and null as 'equal'

https://github.com/microsoft/vscode-languageserver-node/issues/86#issuecomment-245612694

As you said in that comment, many languages don't have a distinction between `null` and `undefined` so your newer statement would make implementation of LSP in those languages a lot more cumbersome (for no obvious benefit?).

For context: https://github.com/felixfbecker/php-language-server/issues/758

I do agree though that it would be nice to list out the available types explicitly with `strictNullChecks` assumed, I just assumed that wasn't the case rn because the spec predates `strictNullChecks`.

**Comment by joaotavora** [comment]
> for no obvious benefit?

... except for supporting clients that follow the specification :wink:
