### ISSUE TITLE
Document state with and without DidOpen/DidClose/DidSave

### ISSUE THREAD

**Issue by kaby76** [microsoft/language-server-protocol#861]
I've been trying to add various servers to a client and have noticed one server that works fine (Eclipse Java) while another that doesn't work from the get-go (Clangd). It turns out that the client never makes a DidOpen call of the document. So with Clangd, it never adds the file to its cache of files that it knows, and returns basically "I have no idea what the hell you are talking about" with every subsequent request on the document.

Reading the spec carefully several times, the spec states that a "DidOpen" is not required, and is implementation-dependent:

"Note that a server’s ability to fulfill requests is independent of whether a text document is open or closed."

Note, the webpage https://microsoft.github.io/language-server-protocol/overview has a sequence diagram that shows the document management calls DidOpen and DidSave, but the spec doesn't say what happens if the client calls DidSave but never made the DidOpen.

Shouldn't the client be made aware of whether these document management calls (DidOpen/DidSave/DidClose) are required for a particular server so it is clear who manages the "truth" of a document?

**Comment by rcjsuen** [comment]
@kaby76 Maybe I'm misunderstanding something but are you saying that clangd does not give you a correct response if you send a `textDocument/formatting` (or whatever) request to it without first having sent it a `textDocument/didOpen` notification? As you noted, language servers should be able to handle this as originally outlined in #177 (and subsequently implemented in #431).

As to your second point, you are suggesting that a server make clear that it supports (or does not support) "arbitrary" requests **without** first having received a `textDocument/didOpen` notification. Is that correct?

**Comment by kdvolder** [comment]
> "Note that a server’s ability to fulfill requests is independent of whether a text document is open or closed."

I'm not sure that's necessarily true for all servers. Some servers may just not be prepared to do anything meaningful unless a document is open because it has no way of knowing what the contents of the document is. As far as I know there are no rules at all about the format and meaning of the document uri's so you would have to make some special assumptions about the uri's to be able to fetch their contents (e.g. if the uri is 'file' type and points to a local file this is all well and good, but what if its something else?).

Anyhow I guess the server can still 'handle' requests like 'give the symbols for this random uri of a not open document' but the only meaningful response it could give without having been given the contents of the document beforehand may very well be 'no symbols'.

**Comment by kdvolder** [comment]
I guess the point of my previous comment is, if we want a server to be able to meaningfully handle requests like 'get me the document symbols' about non-open documents, then the spec needs to clarify how servers can/should obtain the content of such documents.

**Comment by kaby76** [comment]
You are correct in your understanding. Clangd requires the DidOpen call before processing any other requests. (I hacked at Clangd, to fix this, and now it works.)

I would change the wording of "Note that a server’s ability to fulfill requests is independent of whether a text document is open or closed"--which is used in several places in the spec--to something very concrete: "Note, the server does not require Text Synchronization calls as a prerequisite for processing Language Feature calls. See Section .... for further information." At that point, someone can describe the range of possible sequences of calls, go over what "truth" means, go over the editor model, what a workspace is, etc.

While I am here, can I make a recommendation on the spec? I would highly recommend inserting section headings and numbers into the spec's text. It is horribly imprecise to describe where a change might be required. It is easy to say something like: "In Section 10, paragraph 2, sentence 3, I have a problem with ...". I don't understand why these aren't available when scientific and engineering documents for years have used section headings and numbers to label the information concisely.

--Ken

**Comment by kaby76** [comment]
> That server complies with the letter of the spec, it does 'handle' the request, but in spirit its handling is just a "sorry I don't know".

What you say is that it's ok for the server to not handle the request for this client. This kind of goes against the basic premise/promise of the protocol of having any server interoperate with any client. So, as demonstrated by this Clangd example, if I write a server, and I want to say it's compatible with all clients, I'm going to have to test it against all client types, likely all OSes, too. Wonderful.

Further, my interpretation from reading the spec is that textDocument/didOpen is basically a locking mechanism, and the "truth"--as it is currently written--is just a "write lock" on the entire contents of the doc. I'm not sure why the spec doesn't use the well-known and well-understood concept of locking here. A server that requires the didOpen means I can't just look at the file, use the server for markup, even if I don't care to modify it. What a great server.

--Ken

**Comment by kdvolder** [comment]
@kaby76 What I'm saying is that, as a server author the spec is not telling me how I should/can handle a request for information about symbols in a document without making it clear how my server can get the contents of the document. So in that case, from my point of view the only reasonable response to that request is something like an empty list of symbols; or some kind of error.

So basically my point is that, sure the spec can say that the server *must* handle request for document symbols even if the document is not open, but then the spec must make it clear how a server can get content for non-open documents as well. As far as I know the spec says nothing about this at all.

**Comment by kaby76** [comment]
I'm not making demands. I'm trying to point out that the spec is ambiguous and it should be fixed. In fact, I only got into LSP because I wanted to test out a few clients and servers before I wrote my own server for Antlr. In fact, that's not even my primary focus because I'm only using this to flush out the details of a good symbol table for any programming language so I can fit it into my transformation system. Sigh.

If you subscribe to the goal that LSP should be a framework that allows maximum cooperation between clients and servers, then someone (or the controlling body of this spec) is going to need to make some decisions here and make it crystal clear. Otherwise, people are going to keep spinning in circles (#861, #431, #177).

Folks need to decide if they want explicit (open required) or implicit (no open required) locking.

Folks also need to decide how to get the contents of a doc. Clangd gets the contents from the open, but it already reads the file system directly because it needs the #include files to do a compile and build an AST. Getting the contents of #include files only from the client doesn't seem scalable. It already takes 20 s in some cases to compute the AST. How is it going to handle a textDocument/implementation? Where is it going to find the implementation for an unopened, unknown .cpp file?

Food for thought.

--Ken

**Comment by kdvolder** [comment]
@kaby76 I'm not trying to fight with you. I think we are actually in total agreement. I did not say that you are 'making demands'. Unless I misunderstand , I think you are asking the spec to be made more clear that a server should handle requests for stuff like 'document symbols' when document is open or closed both... and... **I agree**.

On top of that I'm saying that it is **also** necessary that the spec should clarify how a server is to obtain the document content for closed documents. So that the server can, in fact, handle the request (because without a way to obtain document content it is really not possible to handle request for document symbols meaningfully).

> Folks also need to decide how to get the contents of a doc. 

If you mean by this phrase that this is something that should be clarified in the spec (?), then I agree. And so, I think this means we are actually 100% in agreement.

**Comment by kaby76** [comment]
Thanks--I guess I was a little sensitive here. All sound good and in agreement. I'll leave it to the governing body to make the changes. --Ken

**Comment by kdvolder** [comment]
NP @kaby76 . I think I may not have made myself clear in my earlier responses :-).

> Further, my interpretation from reading the spec is that textDocument/didOpen is basically a locking mechanism, and the "truth"--as it is currently written--is just a "write lock" on the entire contents of the doc

That's not my interpretation. I was thinking of it more as a mechanic that supports an 'editor' ownining the contents of a document in a 'dirty' in-memory buffer. I.e. the mechanic allows for the editor have a in-memory copy of the document, this copy can diverge from the content on disk (or wherever the content is stored persistently). But since the 'document truth' is owned by the editor the 'true content' of the document is the one that is in the editor, not the one that is on disk, so server should not read the content from disk at this point as it is probably outdated.

**Comment by kaby76** [comment]
So my reason for calling this a lock was this: The spec says that once the client obtains the "truth" (which is the content of the doc), you (the server) can't read the document's truth. _("The document’s truth is now managed by the client and the server must not try to read the document’s truth using the document’s Uri." https://microsoft.github.io/language-server-protocol/specifications/specification-3-14/#textDocument_didOpen)_ On second look, it's a "gentlemen's agreement" because there is nothing really to prevent you (the server) from reading the URI content, the wording being "must not". But, when I first read this, if you agree never to read the content from URI after the open call, the content is mutually exclusive by an implementation, ergo a mutex with the intention that the client will manipulate the content. If you (the server) agrees to only get the content of the doc (or #includes) through the open, you can only reply empty answers to the client for unopened docs, not very useful. I can only imagine how this will work with multiple clients, rollbacks, etc, but it would be pretty interesting.

**Comment by dbaeumer** [comment]
A couple of comments from my end:

- the goal of the LSP is that a server produces results for documents for which he didn't receive and open call.
- a server doesn't manage random documents. It registers for certain document selectors which allows to specify a schema. So if a server can only handle `file` schema it should only register for document URIs which have a file schema.
- for backwards compatibility (and historical reasons) the registrations returned from the initialize call depend on the schema picked by the client (and the client and the server must have the same understanding here). If a server registers dynamically a server has full control over the document selector. I am open to support selectors in the `initialize` call. However it makes the protocol more complicated since it is already available in the `initialized` call.
- having the ability to fetch a URI's content from the server via a client is a known feature request but is IMO independent from this discussion

I am open to make the statements in the spec stronger in terms that the server is supposed to handle  requests for URIs it registered for. I am also open to say that a server can error if it received a request for a document URI it didn't register for.

I am also open to replace truth with something that uses the term lock or to clarify it using the term lock.

**Comment by kdvolder** [comment]
> So if a server can only handle file schema it should only register for document URIs which have a file schema.

That sort of makes sense. Except perhaps that it doesn't really depend on the uri scheme, but on whether or not the server can obtain the contents of the document. I.e. for document which are open, the server can handle them just fine without having its own capability to fetch the document contents, because it is able to track the document content via the text sync events that the client sends.

But when the document is not open... the suddenly the scheme would matter.

> for backwards compatibility (and historical reasons) the registrations returned from the initialize call depend on the schema picked by the client

That is unfortunate because the dynamic registration is optional and not widely supported by all clients.

> having the ability to fetch a URI's content from the server via a client is a known feature request but is IMO independent from this discussion

Okay, sure, I agree, let's treat that as an independent issue. Do you have a link for this?

> I am open to make the statements in the spec stronger in terms that the server is supposed to handle requests for URIs it registered for.

Not sure this is a good idea. See earlier comment. As server I may well just register for all schemes because I want to handle all documents of a certain type (language id) for which I can obtain the content. This ability to obtain the document content is not totally in alignment with the uri scheme since I can *always* obtain document content for open documents independent of the scheme.

> I am also open to replace truth with something that uses the term lock or to clarify it using the term lock.

Personally I don't mind the current wording using the terminology 'document truth'. But I wouldn't object to adding a clarification that uses locking terminology if that makes things easier to understand.

**Comment by kaby76** [comment]
Folks, I had a conversation with Clangd folks (https://llvm.discourse.group/t/clangd-explicit-and-implicit-doc-open/205). Apparently my change of 121 lines out of 24000+ lines of code of Clangd--which would have allowed it to accept Language Feature requests without a prior open--would have driven the program over the top in complexity and so rejected. Yes, a 0.5% code change, which works fine, but only after waiting 60+ seconds for the server to parse and do whatever it must with a 7-line Hello World C++ program. Those folks insist that the client issue an open first thing after an initialize in order to work with Clangd--nevermind that the server already reads a ton of #include files in the file system when parsing. Well, my response to that is there are other C++ LSP servers. Rather than beat this dead horse into a pulp, I'm going to let the chips fall where they may and get work done. Thanks for listening. --Ken
