### ISSUE TITLE
language servers provide "New File" templates

### ISSUE THREAD

**Issue by ags799** [Microsoft/language-server-protocol#88]
What do we think of language servers providing "New File" templates? Eg, a Java language server could advertise "New Java Class" and "New Java Interface" templates, which would correspond to templates like

``` java
{{packageName}}

class {{className}} {
}
```

and

``` java
{{packageName}}

interface {{className}} {
}
```

**Comment by mickaelistria** [comment]
What about making those "new" templates completion proposals when the file is empty? So one creates a new Something.java, gets an empty file, and first completion items are "create class Something", "create interface Something", "create enum Something"...?

**Comment by ags799** [comment]
Sounds good, especially since it fits the existing protocol. I was thinking about an alternative UX story in which the user clicks "New File" and is presented with a set of starting templates, eg {"Java Class", "Java Interface", "Text File"}. I think that would be more intuitive.

But perhaps such a UX story is not worth changing the protocol.

**Comment by felixfbecker** [comment]
I would like to see a `workspace/newDocument` request.
That would be in line with possible requests like `workspace/renameDocument` that can change a namespace/class declaration upon rename/move.

**Comment by dbaeumer** [comment]
To keep the number of issues in our inbox at a manageable level, we’re closing issues that have been on the backlog for a long time but haven’t gained traction: we look at the number of votes the issue has received and the number of duplicate issues filed. Thank you for your time and understanding.

If you disagree and feel that this issue is crucial: we’re happy to listen and to reconsider.


With the new way of contributing implementation and protocol definitions using the describe process here: https://github.com/Microsoft/language-server-protocol/blob/master/contributing.md I think this could come as a proposal.
