### ISSUE TITLE
What is the purpose of the two definitions, SymbolInformation and DocumentSymbol?

### ISSUE THREAD

**Issue by h-michael** [microsoft/language-server-protocol#884]
I make this issue because I did not understand even by looking at past issues.
I'm sorry if I overlooked an issue or document to refer to in the past.

According to document, the response of `textDocument/documentSymbol` has two types defined except for null.
However, neither is deprecated.
`SymbolInformation` has location but no detail.
`DocumentSymbol` has no location, but has properties to represent more detailed information of the symbol such as detail and hierarchy.
Assuming from this, `SymbolInformation` is used for displaying simple information of symbol and jumping to it, and` DocumentSymbol` is used for building outline UI instead of jump because there is no location I thought it was a thing.

If this guess is correct, we think that each should be a different RPC method because they have different uses.

**Comment by KamasamaK** [comment]
I think that the spec should indicate that `DocumentSymbol[]` is preferred. `SymbolInformation[]` is really only there for compatibility. The `SymbolInformation` itself cannot be deprecated because it is still used for the response of `workspace/symbol`.

`DocumentSymbol` doesn't need the full location with URI because it is for a given document, so ranges are sufficient.

**Comment by h-michael** [comment]
> The SymbolInformation itself cannot be deprecated because it is still used for the response of workspace/symbol.

I see that. But if that is only for compatibility, I want to deprecate `SymbolInformation` at `textDocument/documentSymbol`.

> DocumentSymbol doesn't need the full location with URI because it is for a given document, so ranges are sufficient.

Clients can certainly build a location even if `DocumentSymbol` don't have one, but it is easier to handle by giving the location to the response than creating a location by merging the file uri of the request params and the range of the response on the client side.

I have one more question.
`TextDocumentClientCapabilities` has `documentSymbol.hierarchicalDocumentSymbolSupport` and client can send that.
I've expected that if client send `TextDocumentClientCapabilities` with falsey hierarchicalDocumentSymbolSupport, the server response `SymbolInformation` instead of `DocumentSymbol`.
But some servers(ex. [rust-analyzer](https://github.com/rust-analyzer/rust-analyzer/blob/f2291d6a760f8a2d15074b5874facb03f5f838bc/crates/server/src/handlers.rs#L48)) response `DocumentSymbol` with children properties.
Was my expected behavior wrong?
If so, why does the client need to send this capability?

**Comment by Gama11** [comment]
Yeah, technically that doesn't seem correct. But I think in practice a lot of language servers simply don't bother to handle every client capability since they mainly care about VSCode support. Personally I definitely didn't bother to implement and maintain a separate legacy code path for `SymbolInformation` document symbols in the language server I work on.

**Comment by puremourning** [comment]
> But I think in practice a lot of language servers simply don't bother to handle every client capability since they mainly care about VSCode support

sigh.

**Comment by h-michael** [comment]
> But I think in practice a lot of language servers simply don't bother to handle every client capability since they mainly care about VSCode support. 

To me the story of what editor/IDE the server supports sounds nonsense.
Servers and clients only need to implement the protocol specification correctly.
However, there are still many unclear specifications of lsp.
I just want to make it clear so that neither the client nor the server implement the wrong implementation.

We also want to avoid having to insert workaround code for a specific server that has implemented it incorrectly because the server interprets the specification differently.

To do so, we need to eliminate ambiguous specifications.

**Comment by Gama11** [comment]
I don't think there's much ambiguity in this case. If the client says he doesn't support hierachical document symbols, and the server sends them anyway, it can only be the server who is at fault.

I guess the correct course of action for servers that chose to _only_ support hierachical document symbols would be to use dynamic registration for the document symbol request, and only register it in case the client supports hierarchical symbols. That might get a bit tricky though since dynamic registration itself is a capability that technically has to be checked.

**Comment by h-michael** [comment]
If the server changes the return value depending on the value of `hierarchyDocumentSymbolSupport`, the client can handle the value easily.

Now the client implementation has a lot of code like:

```lua

if symbol.location then -- this is the SymbolInformation
	...
else if symbol.detail -- this is the DocumentSymbol
    ...
end
```

Such a workaround is not limited to this response.

**Comment by KamasamaK** [comment]
> > The SymbolInformation itself cannot be deprecated because it is still used for the response of workspace/symbol.
> 
> I see that. But if that is only for compatibility, I want to deprecate `SymbolInformation` at `textDocument/documentSymbol`.

I think you mean `SymbolInformation[]` which is the return type. There is no TSDoc notation to deprecate a return type as far as I am aware, which is why I was justifying why the type itself could not be deprecated in the formal sense. I think the best way to address this is to recommend that `SymbolInformation[]` should only be returned when `DocumentSymbolClientCapabilities.hierarchicalDocumentSymbolSupport` is falsy.


> > DocumentSymbol doesn't need the full location with URI because it is for a given document, so ranges are sufficient.
> 
> Clients can certainly build a location even if `DocumentSymbol` don't have one, but it is easier to handle by giving the location to the response than creating a location by merging the file uri of the request params and the range of the response on the client side.

It may make it easier, but I think the spec intends that these objects provide the minimal amount of information necessary. Anyway, this request was already rejected. See #582

**Comment by dbaeumer** [comment]
The big difference between `DocumetSymbol` and `SymbolInformation` is that the first one can describe a hierarchy and the second only a flat list. 

I am not against deprecating `SymbolInformation` in the context of `textDocument/documentSymbol` but we can't say that if a client set `hierarchicalDocumentSymbolSupport ` to true that the server can only return `DocumetSymbol` since this would be breaking for old clients. The capabilities are used to keep things backwards compatible until we move to a `4.x` version in which we could remove stuff.

**Comment by Gama11** [comment]
>but we can't say that if a client set `hierarchicalDocumentSymbolSupport` to true that the server can only return `DocumetSymbol` since this would be breaking for old clients

But an old client that doesn't support `DocumentSymbol` wouldn't set `hierarchicalDocumentSymbolSupport` to `true` in the first place?

**Comment by dbaeumer** [comment]
Sorry, I meant breaking for old servers. A client might set the property to true but the server might be old not reading the new capability and still returns `SymbolInformation`.

**Comment by KamasamaK** [comment]
> Sorry, I meant breaking for old servers. A client might set the property to true but the server might be old not reading the new capability and still returns `SymbolInformation`.

That is why I said that the spec should "recommend" that usage, not enforce it.

**Comment by dbaeumer** [comment]
@KamasamaK recommending makes sense to me.
