### ISSUE TITLE
(noob question) mininum server setup procedure?

### ISSUE THREAD

**Issue by wisechengyi** [Microsoft/language-server-protocol#89]
Hi,

I would like to try out the project, but was unable find any procedure to spin off a minimum set up. Is there any documentation I can follow in that regard?

Thanks,
Yi

**Comment by akosyakov** [comment]
There are [typescript API](https://code.visualstudio.com/docs/extensions/example-language-server#_implement-your-own-language-server) as well as [java API](https://github.com/TypeFox/ls-api) to implement your language server.

Which language do you want to support? You can build your language from the scratch or use a language frameworks as [Xtext](https://www.eclipse.org/Xtext/).

**Comment by wisechengyi** [comment]
Thank you! Mostly Java/Scala/Python, so I can start with Java one as suggested. Do you know the timeline to support Scala and Python since they are not listed under `more SDKs`?

**Comment by mickaelistria** [comment]
@wisechengyi I think the best way to try out the protocol is to try to contribute to an existing client or server of the protocol.
At the moment, the "followers" on this protocol focus on some individual languages or clients of their interest, they don't own all possible implementations and don't necessarily commit to any possible one.
AFAIK, no-one started a language server for Python.
For Scala, there's this issue you can follow or contribute to https://github.com/ensime/ensime-server/issues/1498

**Comment by dbaeumer** [comment]
To keep the number of issues in our inbox at a manageable level, we’re closing issues that have been on the backlog for a long time but haven’t gained traction: we look at the number of votes the issue has received and the number of duplicate issues filed. Thank you for your time and understanding.

If you disagree and feel that this issue is crucial: we’re happy to listen and to reconsider.
