### ISSUE TITLE
Progress initiated by client

### ISSUE THREAD

**Issue by mschaefer88** [microsoft/language-server-protocol#906]
Last one I promise!

The client may submit an additional property _workDoneToken_ for indicating it may receive progress updates for that request. The issue I have now is the following:

Is the server supposed to call the _window/workDoneProgress/create_ before reporting progress?

Im curious since I can only get it to work if I call the create endpoint first. But doesn't that defeat the purpose of sending the token with the request in the first place? I assumed when doing this the client will already have set up the progress monitor on that specific token and the server can start with begin and report.

Thanks again!

**Comment by mschaefer88** [comment]
Used client is: https://github.com/microsoft/vscode-languageserver-node

**Comment by dbaeumer** [comment]
There are two ways of prgress:

- client created progress. When a user triggers an action you usually see a progress monitor. The UI usually passes down a progress monitor to the mode so that it can report progress. This is speced in LSP using the `workDoneToken`, but *NOT* implemented in VS Code since VS Code doesn't have a progress monitor in its API when calling a language feature (for example find all references). So with a VS Code LSP client the token in currently never set, except for initialize. Things might be different in the future or for other clients like Eclipse which have detailed progress reporting in the UI.
- server initiated progress: the server wants to report progress since it is doing some work not directly related to a request (e.g. indexing the source code). For this you first need to call  `window/workDoneProgress/create`. The idea of that progress is not to now call the method on evey request you get. This is something that we should leave under client control.

Hope that helps. Let me know if it is OK to close the issue.

**Comment by mschaefer88** [comment]
Alright, thanks for the clarification!
That resolves my question!
