### ISSUE TITLE
Should `window/workDoneProgress/create` be a notification?

### ISSUE THREAD

**Issue by robertoaloi** [microsoft/language-server-protocol#923]
Version `3.15` of the protocol introduces a new `window/workDoneProgress/create`. How come does this need to be a `request` initiated by the server? Couldn't that be a simple notification? The reason for asking is that for sending a _request_ the server now needs to keep track of a different series of _request ids_ (from the server to the client), something that (at least in the Erlang LS server) was not needed until now. The response is `void` anyway...

**Comment by kjeremy** [comment]
I was actually wondering the same thing for rust-analyzer.

**Comment by dbaeumer** [comment]
The reason is that the request creates UI and that this could fail. Although the resolved promise is void it could still happen that the promise is rejected in which case the progress token can not be trusted.

And there are other requests already that are sent from the server to the client (e.g. fetching configurations, applying workspace edits, ....)

OK. to close?
