### ISSUE TITLE
Change CompletionList#isIncomplete to CompletionList#incomplete

### ISSUE THREAD

**Issue by svenefftinge** [Microsoft/language-server-protocol#93]
... because it would be more consistent naming, as we don't use the 'is' prefix for all the other boolean properties, too.

**Comment by dbaeumer** [comment]
Agree, but would be breaking. Has to wait for 3.0 and we need to decide whether the breakage is worth it.

**Comment by dbaeumer** [comment]
Thinking about this again there is a reason why we named it isInComplete. In case of absence it defaults to the current default behavior of being complete.

Since this would be breaking and doesn't add any value I am closing this.

If you disagree and feel that this issue is crucial: we’re happy to listen and to reconsider.
