### ISSUE TITLE
Is this really a *language* server?

### ISSUE THREAD

**Issue by mickaelistria** [Microsoft/language-server-protocol#95]
The more I use this protocol, the more I find it totally language independent. I could easily imagine an implementation of a the protocol that is entirely multi-language (for example, opening Eclipse editors in some headless server and retrieving the various values for completion, hover, problems... all that independently of the language; or another example, SonarQube using the protocol to report problems on code, also independently of the language...).
Actually, it seems more to be a "development tools server protocol".
Would it be worth renaming it?

**Comment by mickaelistria** [comment]
FYI, this comment is actually something I was asked when doing a presentation about language servers to a 40-divere-developers audience.

**Comment by bruno-medeiros** [comment]
"Languages Server Protocol" 😉

**Comment by TylerJewell** [comment]
We discussed that in the early stages of the PR work and we concluded that while accurate, it was too much of a mouthful.  And we trimmed it down to a name that had good meaning and could likely stick in the market.

**Comment by mickaelistria** [comment]
And what about "code server protocol" ?

**Comment by TylerJewell** [comment]
Not as clear as "language server".  Why change something that isn't broken?  

The LSP is by many accounts a total success - there are dozens of languages working to adopt it, and multiple IDEs working on it.  Seems that the naming did not get in the way of that achievement.  The primary objective now is to get broader adoption on a name that now has some reasonable brand equity.

**Comment by mickaelistria** [comment]
See initial comment about why I think Language Server is a too narrow name. This name prevents some possible integrations that are language agnostic to be considered.
Code is actually used here as a regular name, it's not related to VSCode. Code is a word that will keep existing for a while as it's pretty accurate and has a clear scope, we shouldn't prevent from using it because there's a product named after that.

**Comment by TylerJewell** [comment]
I am more of a marketing guy than an engineer these days.  And what I can tell you is that there is an exorbitant amount of energy that is expended to build a brand that can reach 100s of companies. Companies, including Red Hat, Codenvy, and Microsoft have allocated real $$$ in preparing materials and other packages that make use of that brand, so any change to a name requires a lot of energy and real $$$ to be spent by these companies to make that change.

So the threshold for changing a name will be different for different audiences.  Technical groups will measure a name on its technical accuracy.  I have a tendency to measure it based upon whether it is successful or not.  If there were situations where vendors who wanted to work with the protocol were avoiding it because of the name, then that would be worrisome and it should be looked at.  However, as your OP note indicated that you are thinking aspirationally and vision-oriented vs. having encountered vendors that have encountered real issues.

**Comment by bruno-medeiros** [comment]
@mickaelistria 
> This name prevents some possible integrations that are language agnostic to be considered.

Such as?

**Comment by mickaelistria** [comment]
@bruno-medeiros If you're developing a code quality tool suich as SonarQube or some ALM integration that can affect code editor and read language server, then you don't realize this protocol can help.

@TylerJewell I'm a technical guy, I don't care about $$$ and marketing (I know it's important and don't disminish their impact, it's not just what drives my concerns), I just care about naming the things by its right name ;) Because of the name giving the impression that the protocol does less than what it can do, I tend to believe it slows down its success by reducing how much people can immediately understand what it can do for them. I didn't realize that the "language server protocol" was already a brand name and that the $$$ already spent made it already kind of stuck. I guess I'll submit that new name in some future if the protocol gets forked then :P

**Comment by TylerJewell** [comment]
The barrier for adoption of new language servers will primarily be the number of tools that have the protocol consistently integrated along with demonstrating that there is fluidity + interoperability of a common base of initial servers.  If that happens, then the flood of new server implementations will open up.  But there are plenty of language servers that are on the sidelines right now because they want to see more consistent implementations.

**Comment by dbaeumer** [comment]
We currently don't have any plans to rename this. It is a well established term now. 

If you disagree and feel that this issue is crucial: we’re happy to listen and to reconsider.
