### ISSUE TITLE
How to implement a Language Server for my custom language?

### ISSUE THREAD

**Issue by kant777** [microsoft/language-server-protocol#964]
How to implement a Language Server for my custom language?

I have a grammar file that allows boolean expressions and certain types and it is written using antlr4. and thats it. Now, What is that I need to do to implement a language server so I can get all the features like autocomplete etc?

Is there a hello world like example somewhere for a simple custom language ?

**Comment by rcjsuen** [comment]
@kant777 Do you have a preference of what programming language you want to use to develop your language server?

If you are familiar with TypeScript you can take a look at the [Language Server Extension Guide](https://code.visualstudio.com/api/language-extensions/language-server-extension-guide) document from the Visual Studio Code team.

**Comment by kant777** [comment]
@rcjsuen Java. But Typescript is also useful for our Frontend team! I just want to see really basic example without reading through all the jargon right away but I will go through all the specs once I start playing around with it. is that possible?

**Comment by angelozerr** [comment]
For language server implemented in Java, see https://github.com/eclipse/lsp4j

@kant777 just one question, when you wish to have this language server? 

I ask you this question because I have in my mind a project which will generate a language server (for the first step with Java LSP4J) from a given grammar written in [JavaCC21](https://github.com/javacc21/javacc21) 

[JavaCC21](https://github.com/javacc21/javacc21) is JavaCC which has been rewritten by @revusky with clean mean and the very interesting part of this project for language server is the `fault tolerant` capability. 

For the moment it's an experimental project, but if you are interested please create issues at https://github.com/javacc21/javacc21/issues

**Comment by revusky** [comment]
Hi, thanks for the plug, Angelo. I should clarify one point though, which is that the JavaCC 21 project itself is not really "experimental". It is _specifically_ the abilty to generate _fault-tolerant_ parsers that, is experimental and highly subject to change, yes. But of course that is functionality that was never present in the legacy JavaCC tool anyway. (And almost certainly never will be!)

I mean to say, if you use JavaCC 21 as a significantly improved version of the older JavaCC, i.e. to generate regular non-fault-tolerant parsers, there is no particular reason to think that it is any less reliable than legacy JavaCC, since the core parser/lexer generation algorithms are the same and it builds and runs all the same testcases that are included with the legacy tool (and a few additional ones!) Also, it includes some much needed new features, such code injection. See:  https://doku.javacc.com/doku.php?id=code_injection_in_javacc_21 Also the INCLUDE instruction allows you to organize your grammar into distinct physical files, something never implemented in legacy JavaCC in 20 years. Here, for example, is how JavaCC 21 implements JSONC (JSON with comments.) https://github.com/javacc21/javacc21/blob/master/examples/json/JSONC.javacc

**Comment by kant777** [comment]
I am still trying to understand what I need to do to take an existing antlr4 grammar like below (P.S got the grammar on the internet but assume mine is similar) and create a LS? 

1) Do I need to rewrite my grammar again in some other framework?

```
grammar arithmetic;

file : equation* EOF;

equation
   : expression relop expression
   ;

expression
   :  expression  POW expression
   |  expression  (TIMES | DIV)  expression
   |  expression  (PLUS | MINUS) expression
   |  LPAREN expression RPAREN
   |  (PLUS | MINUS)* atom
   ;

atom
   : scientific
   | variable
   ;

scientific
   : SCIENTIFIC_NUMBER
   ;

variable
   : VARIABLE
   ;

relop
   : EQ
   | GT
   | LT
   ;


VARIABLE
   : VALID_ID_START VALID_ID_CHAR*
   ;


fragment VALID_ID_START
   : ('a' .. 'z') | ('A' .. 'Z') | '_'
   ;


fragment VALID_ID_CHAR
   : VALID_ID_START | ('0' .. '9')
   ;

//The NUMBER part gets its potential sign from "(PLUS | MINUS)* atom" in the expression rule
SCIENTIFIC_NUMBER
   : NUMBER (E SIGN? UNSIGNED_INTEGER)?
   ;

fragment NUMBER
   : ('0' .. '9') + ('.' ('0' .. '9') +)?
   ;

fragment UNSIGNED_INTEGER
   : ('0' .. '9')+
   ;


fragment E
   : 'E' | 'e'
   ;


fragment SIGN
   : ('+' | '-')
   ;


LPAREN
   : '('
   ;


RPAREN
   : ')'
   ;


PLUS
   : '+'
   ;


MINUS
   : '-'
   ;


TIMES
   : '*'
   ;


DIV
   : '/'
   ;


GT
   : '>'
   ;


LT
   : '<'
   ;


EQ
   : '='
   ;


POINT
   : '.'
   ;


POW
   : '^'
   ;


WS
   : [ \r\n\t] + -> skip
   ;
```

**Comment by kant777** [comment]
@angelozerr sooner the better.

**Comment by angelozerr** [comment]
Here a quick recipe to develop a language server around a given language:

 * you need a `fault tolerant parser` for this language (I think it's the hard part of the language server). Fault tolerant means that your parser must not stop to parse a content on the first error and must try to build an AST. If your parser can manage incremental parsing, it should be better again, but it's not required for language server. Antlr4 gives you the capability to generate a fault tolerant parser, it's good for you.

 * once you have a parser, you must choose the language used to write your language server (Java, TypeScript, etc). Generally if your parser is written in Java, you choose Java as language server, TypeScriopt if your parser is written in TypeScript. It seems Antlr4 can generate the both, but perhaps Java in antlr4 is more robust?

 * once the language is chosen, you can write our own LSP protocol by reading the LSP framework or use a LSP library which does already the job:

 * for TypeScript : https://github.com/microsoft/vscode-languageserver-node
 * for Java: https://github.com/eclipse/lsp4j
 * for other like Python, etc,never played with them

 * the last step is to implement the language server which will consume your parser. As @rcjsuen  said you, if you are in Typecript, see https://code.visualstudio.com/api/language-extensions/language-server-extension-guide, if you wish to use Java with LSP4J, there are not a very good guide, see issue at https://github.com/eclipse/lsp4j/issues/372 

Developing a language server with LSP4J can be long and you will have some bugs to stop correctly for instance the language server (process will not be killed correctly), that's why I think it should be very good to have a tools which generates a language server with the best practices (based on skills). 

The idea to generate a language server from a given language:

* already exists with [XText language server](https://github.com/eclipse/xtext-core/wiki/Language-Server-Protocol) (XText is based on antlr) and you can find [sample](https://github.com/itemis/xtext-languageserver-example). 

* will exist with JavaCC21 once I will implement this tooling (I'm waiting for that JavaCC21 supports correctly fault tolerant to start something). The generated language server will use all the skills that I learn since I develop language server with LSP4J. Even if XText is wonderful, I would like to generate a language server without runtime (XText and antlr have a runtime). The idea is to generate a skeleton for a language server (based on LSP4J for the first step) and you update the code at the hand.

**Comment by Razzeee** [comment]
If you can't tap into the compiler for a fault tolerant parser, implementing it on top of tree sitter is an option https://tree-sitter.github.io/tree-sitter/

It's quiet nice to work with.

**Comment by dbaeumer** [comment]
I will keep the issue open for a while to foster the discussion.
