### ISSUE TITLE
Support WorkspaceEditEntryMetadata

### ISSUE THREAD

**Issue by KamasamaK** [microsoft/language-server-protocol#998]
VS Code recently finalized an API for `WorkspaceEditEntryMetadata` (microsoft/vscode#77728) which facilitates the ability for the client to preview a `WorkspaceEdit`. LSP should also adopt this.

**Comment by KamasamaK** [comment]
@dbaeumer Thanks!

What is the reasoning behind making a new interface `AnnotatedTextEdit` instead of adding `annotation` as an optional property to `TextEdit`?

**Comment by kjeremy** [comment]
@KamasamaK @dbaeumer I was wondering the same thing

**Comment by dbaeumer** [comment]
`TextEdit`s show up in many other places (completion item, formatting, ...) where an annotation is not supported (and very likely never will be). Instead of documenting this with every use of TextEdit I decided to introduce a `AnnotatedTextEdit` and use it in cases where an annotation will be handled by the client.
